In [1]:
import pandas as pd
import csv

col_names = [
    'id_oferta', 'id_usuario', 'target_elegibilidad', 
    'nom_facultad', 'nom_especialidad', 'cargo', 
    'funciones', 'conocimientos', 'experiencia', 
    'experiencia_cv', 'estudios_cv'
]

def leer_dataset(archivo):
    return pd.read_csv(
        archivo, 
        sep=',',               
        quotechar='"',         
        escapechar='\\',       
        engine='python',       
        on_bad_lines='warn',    
        encoding='utf-16',
        header=None,
        names=col_names
    )

df_con = leer_dataset('../datos/dataset_nlp_utf16_contratado.csv')
df_rech = leer_dataset('../datos/dataset_nlp_utf16_rechazado.csv')

df_final = pd.concat([df_con, df_rech], ignore_index=True)

df_final.to_csv(
    '../datos/dataset_nlp_utf16.csv', 
    index=False, 
    encoding='utf-16', 
    sep=',', 
    quoting=csv.QUOTE_ALL, 
    escapechar='\\'
)

print(f"Archivo unificado exitosamente: 'dataset_nlp_utf16.csv'")
print(f"Total de filas: {df_final.shape[0]}")
print(f"Total de columnas: {df_final.shape[1]}")

# Configuración de visualización para inspección final
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 10)

display(df_final)

Archivo unificado exitosamente: 'dataset_nlp_utf16.csv'
Total de filas: 220
Total de columnas: 11

,id_oferta,id_usuario,target_elegibilidad,nom_facultad,nom_especialidad,cargo,funciones,conocimientos,experiencia,experiencia_cv,estudios_cv
0,34635,1002160,1,INGENIERIA INDUSTRIAL Y DE SISTEMAS,INGENIERIA DE SISTEMAS,Analista Programador Junior,"Formar parte de nuestros equipos de desarrollo, programando nuevas funcionalidades o adaptando funcionalidades existentes del ERP a partir de requerimientos internos o de clientes.. Colaborar con la documentación de las funcionalidades existentes del ERP, así como de las herramientas propietarias o de las diversas aplicaciones desarrolladas.. Participar en reuniones técnicas de programación y seguimiento.. Participar en los procesos de implementación y soporte de funcionalidades a clientes.","Conocimientos de Java Script, SQL Server (de preferencia).. Se valorará experiencia en desarrollo o uso de ERPs.. Se valorarán conocimientos de gestión de proyectos ágiles.",Con o sin experiencia,ESPAÃOL ||| Excel ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| Jira Software ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Microsoft Office ||| Microsoft Power BI ||| ORGANIZACIÃN ||| ProgramaciÃ³n en Python ||| SQL Server ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÃN,NaN
1,32700,2256,1,INGENIERIA MECANICA,INGENIERIA MECATRONICA,Ingeniero de Instrumentación,"Desarrollar la ingeniería de su especialidad de Instrumentación para los proyectos llevados a cabo por la cía, cumpliendo con los plazos y parámetros de calidad y costos establecidos.","* Profesional titulado de las carreras de Ing. Electrónica, Mecatrónica o afines.\r\n* Experiencia como ingeniero de DISEÑO en el sector oil&gas (excluyente)\r\n* Experiencia en configuración de PLC, sistemas de control, sistemas de seguridad.\r\n* Experiencia mínima 03 años a más.\r\n* Dominio de idioma inglés comprobado.",Junior = mínimo 03 años en ingeniería de diseño. Senior = no menor 10 años en ingeniería de diseño,"||| Autocad ||| Ejecutivo con experiencia en implementacion y monitoreo de proyectos de desarrollo, estudios de mercado, gestion de ensayos de laboratorio, reformulacion de normas gubernamentales, gestion de sistemas de informacion y administrador de plataforma web. Conocimiento de normativas de servicios publicos, evaluacion de procesos de contratacion del estado. Capacidad de trabajo en equipo y bajo presiÃ³n, asumir retos y orientado a resultados ||| FRANCÃS ||| Habilidades sociales:\r\nEmpatÃ­a, Liderazgo, InterrelaciÃ³n con otros, Escucha activa, PersuasiÃ³n, Capacidad de comunicaciÃ³n.\r\nHabilidades profesionales:\r\nTrabajo en equipo, Liderazgo, NegociaciÃ³n, Control del estrÃ©s, RacionalizaciÃ³n, Capacidad analÃ­tica, Capacidad de sÃ­ntesis, ArgumentaciÃ³n, InnovaciÃ³n y creatividad, Iniciativa ||| IBM - Maximo Asset Management ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Ofimatica ||| ORGANIZACIÃN ||| PORTUGUÃS ||| SAP - M",DiseÃ±o de experimentos
2,34733,10078,1,INGENIERIA MECANICA,INGENIERIA MECATRONICA,GERENTE DE OPERACIONES,"Liderar el plan estratégico de operaciones en mina.. Liderar la concepción, ingeniería, valorización, construcción y supervisión de proyectos de desarrollo en mina.. Analizar las propuestas técnicas para los proyectos mineros.",Conocimientos en instalación de proyectos mineros,Experiencia mínima de 10 años liderando proyectos mineros,"Entrenamiento intensivo en los temas claves de AutomatizaciÃ³n Industrial - Webinar Week 2023 ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÃN ||| ParticipaciÃ³n como proyectista en la Feria y Concurso de Proyectos de InvestigaciÃ³n ABET, con el proyecto âDiseÃ±o de la lÃ³gica de control de un sistema de envasado de aceite y posterior embarque de l ||| ParticipaciÃ³n como proyectista en la Feria y Concurso de Proyectos de InvestigaciÃ³n ABET, con el proyecto âSistema eficiente de riego inteligente para Ã¡reas verdes de zonas urbanas.â ||| ParticipaciÃ³n en la capacitaciÃ³n virtual en IDENTIFICACION DE PELIGROS, EVALUACION DE RIESGOS Y MEDIDAS DE CONTROL ||| REGLAMENTO INTERNO DE SEGURIDAD Y SALUD EN EL TRABAJO ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÃN ||| Trabajos en Altura",NaN
3,32671,6323,1,INGENIERIA MECANICA,INGENIERIA MECANICA Y ELECTRICA,Cotizador de Servicio Técnico Comercial,"01.Apoyar en el soporte técnico a los Ingenieros de Ventas, Vendedor de Servicios, clientes internos y externos, vía telefónica, mail u otro.\r\n02.Elaborar propuestas técnicas o fichas técnicas de la línea STC.\r\n03.Elaborar cotizaciones STC por medio del uso del sistema SAP, así como los entregables que serán dirigidos a los clientes, mediante el uso de plantillas del área.\r\n04.Apoyar en la elaboración de las presentaciones de las propuestas técnicas-comerciales a los Ingenieros de Ventas. Etc.",Basicos,No se requiere experiencia previa en el puesto.,||| Ansys ||| AutoCad ||| Capacidad analÃ­tica y juicio critico ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| Inventor ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Microsoft office ||| MS Project ||| ORGANIZACIÃN ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÃN,"Curso de capacitaciÃ³n llevado a cabo en Buenos Aires para mantenimineto de compresores de aire y oxigeno, secadores, PSA e instrumentacion de plantas de Oxigeno medicinal. ||| Inventor - Nivel Avanzado"
4,36568,1002976,1,INGENIERIA MECANICA,INGENIERIA MECANICA,Ingeniero de Mantenimiento Mecánico,"Cumplir con el programa de mantenimiento preventivo y correctivo para asegurar la operación continua de la planta.\r\nSupervisar e inspeccionar la planta para asegurar el buen funcionamiento de las máquinas en general.\r\nSupervisar la ejecución de los trabajos de mantenimiento correctivo y preventivo de la planta.\r\nMantener registros precisos de mantenimiento, informes de incidentes y mejoras implementadas, proporcionando datos para análisis y toma de decisiones estratégicas.\r\nImplementar mejoras en lo",Bachiller o titulado de las carreras de Ingeniería mecánica o mecatrónica (Indispensable)\r\nExperiencia laboral de 3 años mínimo en el área de mantenimiento en empresas industriales (Indispensable)\r\nOffice nivel avanzado.\r\nDisponibilidad para laborar en la zona sur de Lima,N,AutoCAD ||| Autodesk Inventor ||| CERTIFICADO DE AUTOCAD NIVEL INTERMEDIO ||| CERTIFICADO DE EXCEL NIVEL AVANZADO ||| CERTIFICADO DE KEY USER SAP PM ||| Excel ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Matlab ||| MS Office ||| ORGANIZACIÃN ||| Power BI ||| Python ||| Revit ||| SAP PM y SAP MM ||| SQL Server ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÃN,"||| calculo de la carga tÃ©rmica y estudio de carta psicomÃ©trica ||| Estudio de la Ingenieria de Mantenimiento Correctivo, Preventivo y Predictivo, tambiÃ©n el estudio de la fiabilidad, confiabilidad y el anÃ¡lisis de Weibull. ||| layout, bloques estÃ¡ticos y dinÃ¡micos, planos, etc. ||| Secuencia de comandos e instrucciones grabadas en excel, generar informes y manipular datos, automatizar tareas repetitivas o complejas. ||| Transacciones de mantenimiento, Datos Maestros, GestiÃ³n de avisos de mantenimiento, GestiÃ³n de ordenes de mantenimiento, Mantenimiento preventivo o planificado y sistemas de informaciÃ³n o reportes"
...,...,...,...,...,...,...,...,...,...,...,...
215,26715,2406,0,INGENIERIA QUIMICA Y TEXTIL,INGENIERIA QUIMICA,Ejecutivo de Ventas / Part time (Home Office),NaN,NaN,N,"||| AspenHysys ||| AutoCAD ||| Estudiante del 9no ciclo de IngenierÃ­a QuÃ­mica en la Universidad \nNacional de IngenierÃ­a. Me caracterizo por ser una persona \nproactiva, entusiasta y con muchas ganas de aprender. Cuento \ncon un gran interÃ©s en los procesos y deseo iniciar una lÃ­nea de \ncarrera en dicha Ã¡rea. ||| Excel Empresarial ||| GestiÃ³n Ambiental ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| ITALIANO ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Minitab ||| MS Excel ||| MS Word ||| ORGANIZACIÃN ||| Phyton ||| PowerBI ||| SAP ERP ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÃN","||| Citizen development ||| GestiÃ³n ambiental en la industria, tratamiento de residuos sÃ³lidos. ContaminaciÃ³n del agua, suelo, atmÃ³sfera. Norma ISO 14001: 2015. ||| Normas ISO 9001, ISO 45001, ISO 14001"
216,13460,1777,0,INGENIERIA QUIMICA Y TEXTIL,INGENIERIA QUIMICA,Practicantes de Ingeniera Qumica,-Efectuar visitas guiadas de acuerdo a la programación diaria de la cartera de Clientes de la Empresa.\r\n-Elaborar Informes de carácter Técnico-Ingenieril de las visitas realizadas.\r\n-Participar activamente en los Mantenimientos de Planta programados por la Empresa.\r\n-Mantener y cautelar adecuadamente los instrumentos de monitoreo de Planta a su cargo.\r\n-Cualquier otra función que le asigne el Jefe Inmediato.,Programa Informático Office a nivel Intermedio.\r\nDeseable Curso de Tratamiento de Agua.,N,||| EXCEL ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÃN ||| POWERPOINT ||| PROJECT ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÃN,N
217,22619,86,0,INGENIERIA CIVIL,INGENIERIA CIVIL,Ingeniero Civil Junior.,NaN,NaN,N,||| INNOVACIÃN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÃN ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÃN,N
218,8558,244,0,INGENIERIA INDUSTRIAL Y DE SISTEMAS,INGENIERIA DE SISTEMAS,Practicante de Ingeniería Industrial,"Desarrollo, control y armado de los sistemas de calidad, SSO y medio ambiente \r\nVerificación del cumplimiento de SIG\r\nChequeo de las desviaciones de SIG y desarrollo de sistemas/métodos para evitar la desviación\r\nPreparación para auditorías relacionadas a estos sistemas",Normas ISO 9000\r\nNormas ISO 14000\r\nNormas OHSAS 18000\r\nSistemas integrados de gestión\r\nHerramientas de calidad\r\nGestión de procesos\r\nSeguridad y salud ocupacional\r\nGestión de calidad total\r\nIngeniería y gestión ambiental,N,"||| Bizagui- Modeler ||| Estudiante de Ing. Sistemas de la Universidad Nacional de IngenierÃ­a, perteneciente al tercio superior, con conocimientos y manejo de Microsoft Excel 2016, SQL SERVER â ImplementaciÃ³n y Project, GestiÃ³n de Proyectos y del idioma inglÃ©s a nivel bÃ¡sico. \r\nMe considero autodidacta, proactivo, puntual, innovador, analÃ­tico, creativo, responsable, con habilidad para trabajar en equipo y bajo presiÃ³n, con capacidad para resolver problemas, deseo de superaciÃ³n e iniciativa propia. ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| MS EXCEL ||| MS Project ||| MS SQL Server ||| MS Visio ||| ORGANIZACIÃN ||| Pro-Model 2014 ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÃN","Conocimientos acerca de las Ã¡reas de conocimiento, sobre la documentaciÃ³n en los entregables. El objetivo principal de la GestiÃ³n de Proyectos es administrar, planificar, coordinar, seguimiento y con ||| Entender las definiciones, objetivos y tÃ©cnicas del modelado de procesos de negocio. Definir y proveer una notaciÃ³n estÃ¡ndar que sea fÃ¡cilmente entendible por los involucrados en el proceso de negocio"
219,9329,3758,0,INGENIERIA CIVIL,INGENIERIA CIVIL,Jefe de Campo,"- Supervisar y distribuir las actividades del personal a cargo de acuerdo a los proyectos establecidos.\r\n- Organizar y dirigir el equipo humano así como los medios productivos de la obra para obtener los resultados en los plazos establecidos.\r\n- Supervisar, controlar la distribución y recepción de los materiales requeridos para cada actividad en particular.\r\n- Coordinar con el área de proyectos los materiales que requieren para cada proyecto y proponer aquellos que se requieran para casos particulares.\r\n- Participar en la fase de construcción del proyecto aportando soluciones e ideas que faciliten la operación.\r\n- Asistir y participar como representante de la empresa en las reuniones de coordinación, seguridad.\r\n- Cumplir y hacer cumplir las normas y procedimientos de seguridad y salud en el trabajo establecidos por la organización.",Microsoft Office nivel Intermedio\r\nAUTOCAD\r\n3D MAX\r\nPhotoshop,N,"ArcGis ||| Auto CAD, ||| Civil3D ||| Emprendedor, analÃ­tico, pasiÃ³n por aprender, innovador,\r\nliderazgo de equipos, comunicaciÃ³n asertiva, direcciÃ³n y planeamiento estratÃ©gico, gestiÃ³n del\r\nriesgo, orientaciÃ³n a resultados, capacidad de anÃ¡lisis y alto sentido de la responsabilidad. ||| ESPAÃOL ||| ETABS ||| Formar parte de una empresa de alto prestigio. Asi permita el desarrolllo de la empresa a travÃ©s del crecimiento profesional, el logro de las metas efizcamente y mejoramiento continuo de conocimientos, habilidades, fortalezas e iniciativa ||| INGLÃS ||| JAPONÃS ||| Ms Office ||| Ms Project ||| Primavera, ||| Revit Architecture, ||| S10, ||| SAP 2000, ||| âProfesional de IngenierÃ­a Civil con MBA en curso con 5 aÃ±os de\r\nexperiencia. Especialista en Proyectos y Obras Civiles. InglÃ©s avanzado.â",GestiÃ³n de Proyectos ||| GestiÃ³n en la ConstrucciÃ³n ||| Results of the SATREPS Project: Enhancement of Earthquake and Tsunami Disaster Mitigation Technology in Peru. ||| Taller de Coaching - âDesarrollando habilidades mediante el trabajo en equipoâ ||| Taller de Liderazgo - âLiderando equiposâ. ||| Taller de Seguridad en Obra ||| ValorizaciÃ³n y LiquidaciÃ³n de Contratos de Obra

In [2]:
columnas_texto = [
    'cargo', 'funciones', 'conocimientos', 
    'experiencia', 'experiencia_cv', 'estudios_cv'
]

print("Reemplazando saltos de línea y tabulaciones por espacios.\n")

for col in columnas_texto:
    df_final[col] = df_final[col].str.replace(r'[\r\n\t]+', ' ', regex=True)

display(df_final[columnas_texto].head())

Reemplazando saltos de línea y tabulaciones por espacios.

,cargo,funciones,conocimientos,experiencia,experiencia_cv,estudios_cv
0,Analista Programador Junior,"Formar parte de nuestros equipos de desarrollo, programando nuevas funcionalidades o adaptando funcionalidades existentes del ERP a partir de requerimientos internos o de clientes.. Colaborar con la documentación de las funcionalidades existentes del ERP, así como de las herramientas propietarias o de las diversas aplicaciones desarrolladas.. Participar en reuniones técnicas de programación y seguimiento.. Participar en los procesos de implementación y soporte de funcionalidades a clientes.","Conocimientos de Java Script, SQL Server (de preferencia).. Se valorará experiencia en desarrollo o uso de ERPs.. Se valorarán conocimientos de gestión de proyectos ágiles.",Con o sin experiencia,ESPAÃOL ||| Excel ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| Jira Software ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Microsoft Office ||| Microsoft Power BI ||| ORGANIZACIÃN ||| ProgramaciÃ³n en Python ||| SQL Server ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÃN,NaN
1,Ingeniero de Instrumentación,"Desarrollar la ingeniería de su especialidad de Instrumentación para los proyectos llevados a cabo por la cía, cumpliendo con los plazos y parámetros de calidad y costos establecidos.","* Profesional titulado de las carreras de Ing. Electrónica, Mecatrónica o afines. * Experiencia como ingeniero de DISEÑO en el sector oil&gas (excluyente) * Experiencia en configuración de PLC, sistemas de control, sistemas de seguridad. * Experiencia mínima 03 años a más. * Dominio de idioma inglés comprobado.",Junior = mínimo 03 años en ingeniería de diseño. Senior = no menor 10 años en ingeniería de diseño,"||| Autocad ||| Ejecutivo con experiencia en implementacion y monitoreo de proyectos de desarrollo, estudios de mercado, gestion de ensayos de laboratorio, reformulacion de normas gubernamentales, gestion de sistemas de informacion y administrador de plataforma web. Conocimiento de normativas de servicios publicos, evaluacion de procesos de contratacion del estado. Capacidad de trabajo en equipo y bajo presiÃ³n, asumir retos y orientado a resultados ||| FRANCÃS ||| Habilidades sociales: EmpatÃ­a, Liderazgo, InterrelaciÃ³n con otros, Escucha activa, PersuasiÃ³n, Capacidad de comunicaciÃ³n. Habilidades profesionales: Trabajo en equipo, Liderazgo, NegociaciÃ³n, Control del estrÃ©s, RacionalizaciÃ³n, Capacidad analÃ­tica, Capacidad de sÃ­ntesis, ArgumentaciÃ³n, InnovaciÃ³n y creatividad, Iniciativa ||| IBM - Maximo Asset Management ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Ofimatica ||| ORGANIZACIÃN ||| PORTUGUÃS ||| SAP - M",DiseÃ±o de experimentos
2,GERENTE DE OPERACIONES,"Liderar el plan estratégico de operaciones en mina.. Liderar la concepción, ingeniería, valorización, construcción y supervisión de proyectos de desarrollo en mina.. Analizar las propuestas técnicas para los proyectos mineros.",Conocimientos en instalación de proyectos mineros,Experiencia mínima de 10 años liderando proyectos mineros,"Entrenamiento intensivo en los temas claves de AutomatizaciÃ³n Industrial - Webinar Week 2023 ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÃN ||| ParticipaciÃ³n como proyectista en la Feria y Concurso de Proyectos de InvestigaciÃ³n ABET, con el proyecto âDiseÃ±o de la lÃ³gica de control de un sistema de envasado de aceite y posterior embarque de l ||| ParticipaciÃ³n como proyectista en la Feria y Concurso de Proyectos de InvestigaciÃ³n ABET, con el proyecto âSistema eficiente de riego inteligente para Ã¡reas verdes de zonas urbanas.â ||| ParticipaciÃ³n en la capacitaciÃ³n virtual en IDENTIFICACION DE PELIGROS, EVALUACION DE RIESGOS Y MEDIDAS DE CONTROL ||| REGLAMENTO INTERNO DE SEGURIDAD Y SALUD EN EL TRABAJO ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÃN ||| Trabajos en Altura",NaN
3,Cotizador de Servicio Técnico Comercial,"01.Apoyar en el soporte técnico a los Ingenieros de Ventas, Vendedor de Servicios, clientes internos y externos, vía telefónica, mail u otro. 02.Elaborar propuestas técnicas o fichas técnicas de la línea STC. 03.Elaborar cotizaciones STC por medio del uso del sistema SAP, así como los entregables que serán dirigidos a los clientes, mediante el uso de plantillas del área. 04.Apoyar en la elaboración de las presentaciones de las propuestas técnicas-comerciales a los Ingenieros de Ventas. Etc.",Basicos,No se requiere experiencia previa en el puesto.,||| Ansys ||| AutoCad ||| Capacidad analÃ­tica y juicio critico ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| Inventor ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Microsoft office ||| MS Project ||| ORGANIZACIÃN ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÃN,"Curso de capacitaciÃ³n llevado a cabo en Buenos Aires para mantenimineto de compresores de aire y oxigeno, secadores, PSA e instrumentacion de plantas de Oxigeno medicinal. ||| Inventor - Nivel Avanzado"
4,Ingeniero de Mantenimiento Mecánico,"Cumplir con el programa de mantenimiento preventivo y correctivo para asegurar la operación continua de la planta. Supervisar e inspeccionar la planta para asegurar el buen funcionamiento de las máquinas en general. Supervisar la ejecución de los trabajos de mantenimiento correctivo y preventivo de la planta. Mantener registros precisos de mantenimiento, informes de incidentes y mejoras implementadas, proporcionando datos para análisis y toma de decisiones estratégicas. Implementar mejoras en lo",Bachiller o titulado de las carreras de Ingeniería mecánica o mecatrónica (Indispensable) Experiencia laboral de 3 años mínimo en el área de mantenimiento en empresas industriales (Indispensable) Office nivel avanzado. Disponibilidad para laborar en la zona sur de Lima,N,AutoCAD ||| Autodesk Inventor ||| CERTIFICADO DE AUTOCAD NIVEL INTERMEDIO ||| CERTIFICADO DE EXCEL NIVEL AVANZADO ||| CERTIFICADO DE KEY USER SAP PM ||| Excel ||| INGLÃS ||| INNOVACIÃN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÃN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Matlab ||| MS Office ||| ORGANIZACIÃN ||| Power BI ||| Python ||| Revit ||| SAP PM y SAP MM ||| SQL Server ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÃN,"||| calculo de la carga tÃ©rmica y estudio de carta psicomÃ©trica ||| Estudio de la Ingenieria de Mantenimiento Correctivo, Preventivo y Predictivo, tambiÃ©n el estudio de la fiabilidad, confiabilidad y el anÃ¡lisis de Weibull. ||| layout, bloques estÃ¡ticos y dinÃ¡micos, planos, etc. ||| Secuencia de comandos e instrucciones grabadas en excel, generar informes y manipular datos, automatizar tareas repetitivas o complejas. ||| Transacciones de mantenimiento, Datos Maestros, GestiÃ³n de avisos de mantenimiento, GestiÃ³n de ordenes de mantenimiento, Mantenimiento preventivo o planificado y sistemas de informaciÃ³n o reportes"

In [3]:
import re

def buscar_caracteres_extranos(df, patron):
    columnas_con_extranos = {}
    print("Buscando caracteres extraños.\n")

    for col in df.columns:
        if df[col].dtype == 'object':
            textos = df[col].dropna().astype(str)

            caracteres = textos.str.findall(patron).explode().dropna().unique()
            

            caracteres = [c for c in caracteres if c.strip() != '']

            if len(caracteres) > 0:
                columnas_con_extranos[col] = caracteres

    if columnas_con_extranos:
        print("Se encontraron caracteres extraños en las siguientes columnas:")
        for col, chars in columnas_con_extranos.items():
            print(f" -> Columna '{col}': {chars}")
    else:
        print("No se encontraron caracteres extraños en ninguna columna.")

In [4]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\-]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['/', '+', '(', ')', '\x96']
 -> Columna 'funciones': [':', '{', ';', '"', '|', '}', '(', '+', ')', '/', '>', '&', '\x95']
 -> Columna 'conocimientos': ['(', ')', '*', '&', '\x95', ':', '{', ';', '"', '/', '|', '}', '+', '@']
 -> Columna 'experiencia': ['=', ';', '(', ')', ':', '{', '"', '}', '+', '/', '\x95']
 -> Columna 'experiencia_cv': ['Ã', '\x91', '|', '\x89', '\x93', '³', ':', '\xad', '©', 'â', '\x80', '\x9c', '±', '¡', '\x9d', '\x92', '(', ')', '\x81', '/', '&', '+', '\x9a', 'º', '\x8d', '#', '\x99', '?', '=', '%', ';', 'Â', '´', "'", '_', '"', '\x83', '\x96', '°', '²', ']', '¢']
 -> Columna 'estudios_cv': ['Ã', '±', '³', '|', '©', '¡', '\xad', 'º', '\x8d', '\x93', '\x89', ':', ';', '\x81', '+', '&', '(', ')', '/', 'Â', '²', '\x91', 'â', '\x80', '\x9d', '?', '\x9a', '\x9c']

In [5]:
# Se buscó la representación de caracteres especiales para la limpieza
diccionario_tildes = {
    'Ã\x81': 'Á',
    'Ã\x89': 'É',
    'Ã\x8d': 'Í',
    'Ã\x93': 'Ó',
    'Ã\x9a': 'Ú',
    'Ã\x91': 'Ñ',
    
    'Ã¡': 'á',
    'Ã©': 'é',
    'Ã\xad': 'í',
    'Ã³': 'ó',
    'Ãº': 'ú',
    'Ã±': 'ñ'
}

print("Restaurando tildes y eñes.\n")

for col in columnas_texto:
    for mal, bien in diccionario_tildes.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

display(df_final[columnas_texto].head())

Restaurando tildes y eñes.

,cargo,funciones,conocimientos,experiencia,experiencia_cv,estudios_cv
0,Analista Programador Junior,"Formar parte de nuestros equipos de desarrollo, programando nuevas funcionalidades o adaptando funcionalidades existentes del ERP a partir de requerimientos internos o de clientes.. Colaborar con la documentación de las funcionalidades existentes del ERP, así como de las herramientas propietarias o de las diversas aplicaciones desarrolladas.. Participar en reuniones técnicas de programación y seguimiento.. Participar en los procesos de implementación y soporte de funcionalidades a clientes.","Conocimientos de Java Script, SQL Server (de preferencia).. Se valorará experiencia en desarrollo o uso de ERPs.. Se valorarán conocimientos de gestión de proyectos ágiles.",Con o sin experiencia,ESPAÑOL ||| Excel ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| Jira Software ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Microsoft Office ||| Microsoft Power BI ||| ORGANIZACIÓN ||| Programación en Python ||| SQL Server ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,NaN
1,Ingeniero de Instrumentación,"Desarrollar la ingeniería de su especialidad de Instrumentación para los proyectos llevados a cabo por la cía, cumpliendo con los plazos y parámetros de calidad y costos establecidos.","* Profesional titulado de las carreras de Ing. Electrónica, Mecatrónica o afines. * Experiencia como ingeniero de DISEÑO en el sector oil&gas (excluyente) * Experiencia en configuración de PLC, sistemas de control, sistemas de seguridad. * Experiencia mínima 03 años a más. * Dominio de idioma inglés comprobado.",Junior = mínimo 03 años en ingeniería de diseño. Senior = no menor 10 años en ingeniería de diseño,"||| Autocad ||| Ejecutivo con experiencia en implementacion y monitoreo de proyectos de desarrollo, estudios de mercado, gestion de ensayos de laboratorio, reformulacion de normas gubernamentales, gestion de sistemas de informacion y administrador de plataforma web. Conocimiento de normativas de servicios publicos, evaluacion de procesos de contratacion del estado. Capacidad de trabajo en equipo y bajo presión, asumir retos y orientado a resultados ||| FRANCÉS ||| Habilidades sociales: Empatía, Liderazgo, Interrelación con otros, Escucha activa, Persuasión, Capacidad de comunicación. Habilidades profesionales: Trabajo en equipo, Liderazgo, Negociación, Control del estrés, Racionalización, Capacidad analítica, Capacidad de síntesis, Argumentación, Innovación y creatividad, Iniciativa ||| IBM - Maximo Asset Management ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Ofimatica ||| ORGANIZACIÓN ||| PORTUGUÉS ||| SAP - M",Diseño de experimentos
2,GERENTE DE OPERACIONES,"Liderar el plan estratégico de operaciones en mina.. Liderar la concepción, ingeniería, valorización, construcción y supervisión de proyectos de desarrollo en mina.. Analizar las propuestas técnicas para los proyectos mineros.",Conocimientos en instalación de proyectos mineros,Experiencia mínima de 10 años liderando proyectos mineros,"Entrenamiento intensivo en los temas claves de Automatización Industrial - Webinar Week 2023 ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÓN ||| Participación como proyectista en la Feria y Concurso de Proyectos de Investigación ABET, con el proyecto âDiseño de la lógica de control de un sistema de envasado de aceite y posterior embarque de l ||| Participación como proyectista en la Feria y Concurso de Proyectos de Investigación ABET, con el proyecto âSistema eficiente de riego inteligente para áreas verdes de zonas urbanas.â ||| Participación en la capacitación virtual en IDENTIFICACION DE PELIGROS, EVALUACION DE RIESGOS Y MEDIDAS DE CONTROL ||| REGLAMENTO INTERNO DE SEGURIDAD Y SALUD EN EL TRABAJO ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN ||| Trabajos en Altura",NaN
3,Cotizador de Servicio Técnico Comercial,"01.Apoyar en el soporte técnico a los Ingenieros de Ventas, Vendedor de Servicios, clientes internos y externos, vía telefónica, mail u otro. 02.Elaborar propuestas técnicas o fichas técnicas de la línea STC. 03.Elaborar cotizaciones STC por medio del uso del sistema SAP, así como los entregables que serán dirigidos a los clientes, mediante el uso de plantillas del área. 04.Apoyar en la elaboración de las presentaciones de las propuestas técnicas-comerciales a los Ingenieros de Ventas. Etc.",Basicos,No se requiere experiencia previa en el puesto.,||| Ansys ||| AutoCad ||| Capacidad analítica y juicio critico ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| Inventor ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Microsoft office ||| MS Project ||| ORGANIZACIÓN ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,"Curso de capacitación llevado a cabo en Buenos Aires para mantenimineto de compresores de aire y oxigeno, secadores, PSA e instrumentacion de plantas de Oxigeno medicinal. ||| Inventor - Nivel Avanzado"
4,Ingeniero de Mantenimiento Mecánico,"Cumplir con el programa de mantenimiento preventivo y correctivo para asegurar la operación continua de la planta. Supervisar e inspeccionar la planta para asegurar el buen funcionamiento de las máquinas en general. Supervisar la ejecución de los trabajos de mantenimiento correctivo y preventivo de la planta. Mantener registros precisos de mantenimiento, informes de incidentes y mejoras implementadas, proporcionando datos para análisis y toma de decisiones estratégicas. Implementar mejoras en lo",Bachiller o titulado de las carreras de Ingeniería mecánica o mecatrónica (Indispensable) Experiencia laboral de 3 años mínimo en el área de mantenimiento en empresas industriales (Indispensable) Office nivel avanzado. Disponibilidad para laborar en la zona sur de Lima,N,AutoCAD ||| Autodesk Inventor ||| CERTIFICADO DE AUTOCAD NIVEL INTERMEDIO ||| CERTIFICADO DE EXCEL NIVEL AVANZADO ||| CERTIFICADO DE KEY USER SAP PM ||| Excel ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Matlab ||| MS Office ||| ORGANIZACIÓN ||| Power BI ||| Python ||| Revit ||| SAP PM y SAP MM ||| SQL Server ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,"||| calculo de la carga térmica y estudio de carta psicométrica ||| Estudio de la Ingenieria de Mantenimiento Correctivo, Preventivo y Predictivo, también el estudio de la fiabilidad, confiabilidad y el análisis de Weibull. ||| layout, bloques estáticos y dinámicos, planos, etc. ||| Secuencia de comandos e instrucciones grabadas en excel, generar informes y manipular datos, automatizar tareas repetitivas o complejas. ||| Transacciones de mantenimiento, Datos Maestros, Gestión de avisos de mantenimiento, Gestión de ordenes de mantenimiento, Mantenimiento preventivo o planificado y sistemas de información o reportes"

In [6]:
diccionario_reemplazos = {
    'â\x80\x9c': '"',
    'â\x80\x9d': '"',
    'â\x80\x99': "'",
    'â\x80\x92': '-',
    '\x95': ' ',
    '\x96': '-',
    'Âº': 'º',
    'Â°': '°',
    'Â´': "'"
}

print("Estandarizando comillas, guiones y símbolos especiales.\n")

for col in columnas_texto:
    for mal, bien in diccionario_reemplazos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Estandarizando comillas, guiones y símbolos especiales.

In [7]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['.', '-', '/', '+', ',', '(', ')']
 -> Columna 'funciones': [',', '.', '-', ':', '{', ';', '"', '|', '}', '(', '+', ')', '/', '>', '&']
 -> Columna 'conocimientos': [',', '(', ')', '.', '*', '&', ':', '{', ';', '"', '/', '|', '}', '+', '-', '@']
 -> Columna 'experiencia': ['=', '.', ';', '(', ')', ',', ':', '{', '"', '}', '+', '/']
 -> Columna 'experiencia_cv': ['|', ',', '.', ':', '-', '"', 'Ã', '\x80', '\x92', '(', ')', '/', '&', '+', '#', "'", '?', '=', '%', 'â', '\x93', ';', '\x9c', '_', '\x83', '°', '²', ']', '¢']
 -> Columna 'estudios_cv': [',', '.', '|', '-', ':', ';', '+', '&', '(', ')', '/', 'Â', '\xad', 'Ã', '²', '"', '?', 'â', '\x80', '\x93']

In [8]:
def inspeccionar_contexto(df, caracter, columnas, ventana=40, max_ejemplos=5):
    print(f"Buscando el carácter: {repr(caracter)}\n")

    encontrado_en_total = False

    for col in columnas:
        if df[col].dtype == 'object':
            textos = df[col].dropna().astype(str)

            mascara = textos.str.contains(caracter, regex=False)
            filas_con_caracter = textos[mascara]

            if not filas_con_caracter.empty:
                encontrado_en_total = True
                print(f"=== Columna '{col}' ({len(filas_con_caracter)} apariciones) ===")

                for idx, texto in filas_con_caracter.head(max_ejemplos).items():
                    pos = texto.find(caracter)

                    inicio = max(0, pos - ventana)
                    fin = min(len(texto), pos + len(caracter) + ventana)

                    fragmento = texto[inicio:fin]

                    fragmento_resaltado = fragmento.replace(caracter, f" >>>{caracter}<<< ")
                    
                    print(f" Fila {idx}: ...{fragmento_resaltado}...")
                print("-" * 60)
                
    if not encontrado_en_total:
        print(f"El carácter {repr(caracter)} no se encontró en las columnas indicadas.")

In [9]:
inspeccionar_contexto(df_final, '\x80', columnas_texto)

Buscando el carácter: '\x80'

=== Columna 'experiencia_cv' (8 apariciones) ===
 Fila 6: ...ANÃ >>><<< LISIS DE DATOS CON EXCEL ||| Ansys ||| A...
 Fila 63: ...| AutoCAD ||| Curso taller de oratoria â >>><<<  Centro Cultural UNI- (octubre 2022) ||...
 Fila 137: ...SIMULACIÓN PARA INGENIERÍA DE PROCESOS â >>><<<  CHEMCAD ||| Titulado en Ingeniería Quí...
 Fila 167: ... 5 CONCRETO ARMADO (DISEÑO ESTRUCTURAL â >>><<<  USO DE SOFTWARES) 6 INGENIERÍA SISMO R...
 Fila 203: ... DE INGENIERIA 2016-1. ||| SETAS POWER:â >>><<< ¢ Líder y fundadora del proyecto finalis...
------------------------------------------------------------
=== Columna 'estudios_cv' (1 apariciones) ===
 Fila 137: ...SIMULACIÓN PARA INGENIERÍA DE PROCESOS â >>><<<  CHEMCAD â >>><<<  2007...
------------------------------------------------------------

In [10]:
diccionario_hallazgos = {
    'Ã\x80': 'Á',
    'â\x80“': '-',
    'â\x80\x93': '-',
    'â\x80¢': ' '
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['experiencia_cv','estudios_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [11]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['.', '-', '/', '+', ',', '(', ')']
 -> Columna 'funciones': [',', '.', '-', ':', '{', ';', '"', '|', '}', '(', '+', ')', '/', '>', '&']
 -> Columna 'conocimientos': [',', '(', ')', '.', '*', '&', ':', '{', ';', '"', '/', '|', '}', '+', '-', '@']
 -> Columna 'experiencia': ['=', '.', ';', '(', ')', ',', ':', '{', '"', '}', '+', '/']
 -> Columna 'experiencia_cv': ['|', ',', '.', ':', '-', '"', 'Ã', '\x92', '(', ')', '/', '&', '+', '#', "'", '?', '=', '%', ';', '\x9c', '_', '\x83', '°', '²', ']']
 -> Columna 'estudios_cv': [',', '.', '|', '-', ':', ';', '+', '&', '(', ')', '/', 'Â', '\xad', 'Ã', '²', '"', '?']

In [12]:
inspeccionar_contexto(df_final, '\x9c', columnas_texto)

Buscando el carácter: '\x9c'

=== Columna 'experiencia_cv' (2 apariciones) ===
 Fila 77: ...N JAVASCRIPT ||| PROGRAMACIÓN NEUROLINGÃ >>><<< ÍSTICA ||| PYTHON ||| SUPERVISOR SSOMA |...
 Fila 78: ...N JAVASCRIPT ||| PROGRAMACIÓN NEUROLINGÃ >>><<< ÍSTICA ||| PYTHON ||| SUPERVISOR SSOMA |...
------------------------------------------------------------

In [13]:
diccionario_hallazgos = {
    'Ã\x9c': 'Ü'
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['experiencia_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [14]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['.', '-', '/', '+', ',', '(', ')']
 -> Columna 'funciones': [',', '.', '-', ':', '{', ';', '"', '|', '}', '(', '+', ')', '/', '>', '&']
 -> Columna 'conocimientos': [',', '(', ')', '.', '*', '&', ':', '{', ';', '"', '/', '|', '}', '+', '-', '@']
 -> Columna 'experiencia': ['=', '.', ';', '(', ')', ',', ':', '{', '"', '}', '+', '/']
 -> Columna 'experiencia_cv': ['|', ',', '.', ':', '-', '"', 'Ã', '\x92', '(', ')', '/', '&', '+', '#', "'", '?', '=', '%', ';', '_', '\x83', '°', '²', ']']
 -> Columna 'estudios_cv': [',', '.', '|', '-', ':', ';', '+', '&', '(', ')', '/', 'Â', '\xad', 'Ã', '²', '"', '?']

In [15]:
inspeccionar_contexto(df_final, '\x92', columnas_texto)

Buscando el carácter: '\x92'

=== Columna 'experiencia_cv' (1 apariciones) ===
 Fila 6: ...LECTRIC Y PRO PANEL ||| EPLAN ||| GESTIÃ >>><<< N DE PROYECTOS 1 ||| GESTIÓN DE PROYECTO...
------------------------------------------------------------

In [16]:
diccionario_hallazgos = {
    'Ã\x92': 'Ó'
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['experiencia_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [17]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['.', '-', '/', '+', ',', '(', ')']
 -> Columna 'funciones': [',', '.', '-', ':', '{', ';', '"', '|', '}', '(', '+', ')', '/', '>', '&']
 -> Columna 'conocimientos': [',', '(', ')', '.', '*', '&', ':', '{', ';', '"', '/', '|', '}', '+', '-', '@']
 -> Columna 'experiencia': ['=', '.', ';', '(', ')', ',', ':', '{', '"', '}', '+', '/']
 -> Columna 'experiencia_cv': ['|', ',', '.', ':', '-', '"', '(', ')', '/', '&', '+', '#', "'", '?', '=', '%', ';', '_', 'Ã', '\x83', '°', '²', ']']
 -> Columna 'estudios_cv': [',', '.', '|', '-', ':', ';', '+', '&', '(', ')', '/', 'Â', '\xad', 'Ã', '²', '"', '?']

In [18]:
inspeccionar_contexto(df_final, '\x83', columnas_texto)

Buscando el carácter: '\x83'

=== Columna 'experiencia_cv' (1 apariciones) ===
 Fila 164: ...icos. ||| EXCEL ||| INGLÉS ||| INNOVACIÃ >>><<< "N Y CREATIVIDAD ||| INVENTOR  ||| La ca...
------------------------------------------------------------

In [19]:
diccionario_hallazgos = {
    'Ã\x83': 'Ó'
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['experiencia_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [20]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['.', '-', '/', '+', ',', '(', ')']
 -> Columna 'funciones': [',', '.', '-', ':', '{', ';', '"', '|', '}', '(', '+', ')', '/', '>', '&']
 -> Columna 'conocimientos': [',', '(', ')', '.', '*', '&', ':', '{', ';', '"', '/', '|', '}', '+', '-', '@']
 -> Columna 'experiencia': ['=', '.', ';', '(', ')', ',', ':', '{', '"', '}', '+', '/']
 -> Columna 'experiencia_cv': ['|', ',', '.', ':', '-', '"', '(', ')', '/', '&', '+', '#', "'", '?', '=', '%', ';', '_', 'Ã', '°', '²', ']']
 -> Columna 'estudios_cv': [',', '.', '|', '-', ':', ';', '+', '&', '(', ')', '/', 'Â', '\xad', 'Ã', '²', '"', '?']

In [21]:
inspeccionar_contexto(df_final, '\xad', columnas_texto)

Buscando el carácter: '\xad'

=== Columna 'estudios_cv' (1 apariciones) ===
 Fila 107: ...||| Impartido por: Ing. András Muñoz DíÂ >>>­<<< az ||| Impartido por: Ing. Mariano Schis...
------------------------------------------------------------

In [24]:
diccionario_hallazgos = {
    'Â\xad': ''
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['estudios_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [25]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['.', '-', '/', '+', ',', '(', ')']
 -> Columna 'funciones': [',', '.', '-', ':', '{', ';', '"', '|', '}', '(', '+', ')', '/', '>', '&']
 -> Columna 'conocimientos': [',', '(', ')', '.', '*', '&', ':', '{', ';', '"', '/', '|', '}', '+', '-', '@']
 -> Columna 'experiencia': ['=', '.', ';', '(', ')', ',', ':', '{', '"', '}', '+', '/']
 -> Columna 'experiencia_cv': ['|', ',', '.', ':', '-', '"', '(', ')', '/', '&', '+', '#', "'", '?', '=', '%', ';', '_', 'Ã', '°', '²', ']']
 -> Columna 'estudios_cv': [',', '.', '|', '-', ':', ';', '+', '&', '(', ')', '/', 'Ã', '²', '"', '?']

In [26]:
inspeccionar_contexto(df_final, 'Ã', columnas_texto)

Buscando el carácter: 'Ã'

=== Columna 'experiencia_cv' (2 apariciones) ===
 Fila 165: ...P ||| Especialización en Comunicaciones  >>>Ã<<< -pticas ||| Especialización en Planta Ex...
 Fila 180: ... ||| PORTUGUÉS ||| Power BI ||| Producci >>>Ã<<< ²n ||| Qlick Sense ||| TOMA DE DECISIONE...
------------------------------------------------------------
=== Columna 'estudios_cv' (1 apariciones) ===
 Fila 115: ...ado hasta nivel avanzado con certificaci >>>Ã<<< ²n MET (Michigan English Test Certificat...
------------------------------------------------------------

In [27]:
diccionario_hallazgos = {
    'Ã-': 'Ó',
    'Ã²': 'ó'
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['experiencia_cv','estudios_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [28]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['.', '-', '/', '+', ',', '(', ')']
 -> Columna 'funciones': [',', '.', '-', ':', '{', ';', '"', '|', '}', '(', '+', ')', '/', '>', '&']
 -> Columna 'conocimientos': [',', '(', ')', '.', '*', '&', ':', '{', ';', '"', '/', '|', '}', '+', '-', '@']
 -> Columna 'experiencia': ['=', '.', ';', '(', ')', ',', ':', '{', '"', '}', '+', '/']
 -> Columna 'experiencia_cv': ['|', ',', '.', ':', '-', '"', '(', ')', '/', '&', '+', '#', "'", '?', '=', '%', ';', '_', '°', ']']
 -> Columna 'estudios_cv': [',', '.', '|', '-', ':', ';', '+', '&', '(', ')', '/', '"', '?']

In [29]:
inspeccionar_contexto(df_final, '?', columnas_texto)

Buscando el carácter: '?'

=== Columna 'experiencia_cv' (1 apariciones) ===
 Fila 46: ...oud.tecsup.edu.pe/pcc/#/home/certificado >>>?<<< c=793362&n=P.ESP%2FD%2F25%2F53&t=E ||| I...
------------------------------------------------------------
=== Columna 'estudios_cv' (1 apariciones) ===
 Fila 137: ... >>>?<<<  SOFTWARE DE SIMULACIÓN PARA INGENIERÍA ...
------------------------------------------------------------

In [30]:
diccionario_hallazgos = {
    '?': ''
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['estudios_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [31]:
# Ver el texto completo de la fila 46 en la columna 'experiencia_cv'
print(df_final.loc[46, 'experiencia_cv'])

https://academico-cloud.tecsup.edu.pe/pcc/#/home/certificado?c=793362&n=P.ESP%2FD%2F25%2F53&t=E ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÓN ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN

In [33]:
patron_url = r'(https?://\S+|www\.\S+|\S+\.\w+/\S+)'

print("Revisando URLs y enlaces en las columnas.\n")

for col in columnas_texto:
    if df_final[col].dtype == 'object':
        textos = df_final[col].dropna().astype(str)

        enlaces_encontrados = textos.str.findall(patron_url).explode().dropna().unique()

        if len(enlaces_encontrados) > 0:
            print(f"=== Columna '{col}' ===")
            print(f"Enlaces detectados por el patrón Regex ({len(enlaces_encontrados)} únicos):")

            for enlace in enlaces_encontrados[:10]:
                print(f"   -> {enlace}")

            print("-" * 70)

Revisando URLs y enlaces en las columnas.

=== Columna 'experiencia_cv' ===
Enlaces detectados por el patrón Regex (1 únicos):
   -> https://academico-cloud.tecsup.edu.pe/pcc/#/home/certificado?c=793362&n=P.ESP%2FD%2F25%2F53&t=E
----------------------------------------------------------------------

In [34]:
print("Eliminando URLs...\n")

for col in columnas_texto:
    if df_final[col].dtype == 'object':
        df_final[col] = df_final[col].str.replace(patron_url, ' ', regex=True)

print("¡URLs eliminadas exitosamente!\n")

print("Resultado en la fila 46:")
print(df_final.loc[46, 'experiencia_cv'])

Eliminando URLs...

¡URLs eliminadas exitosamente!

Resultado en la fila 46:
  ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÓN ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN

In [35]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['.', '-', '/', '+', ',', '(', ')']
 -> Columna 'funciones': [',', '.', '-', ':', '{', ';', '"', '|', '}', '(', '+', ')', '/', '>', '&']
 -> Columna 'conocimientos': [',', '(', ')', '.', '*', '&', ':', '{', ';', '"', '/', '|', '}', '+', '-', '@']
 -> Columna 'experiencia': ['=', '.', ';', '(', ')', ',', ':', '{', '"', '}', '+', '/']
 -> Columna 'experiencia_cv': ['|', ',', '.', ':', '-', '"', '(', ')', '/', '&', '+', '#', "'", ';', '_', '°', ']']
 -> Columna 'estudios_cv': [',', '.', '|', '-', ':', ';', '+', '&', '(', ')', '/', '"']

In [36]:
inspeccionar_contexto(df_final, '/', columnas_texto)

Buscando el carácter: '/'

=== Columna 'cargo' (4 apariciones) ===
 Fila 21: ...TÉCNICO ELECTRICISTA >>>/<<<  INSTALACIÓN DE BOMBAS HIDRÁULICAS...
 Fila 183: ...Ejecutivo de Ventas  >>>/<<<  Part time (Home Office)...
 Fila 200: ...Ejecutivo de Ventas  >>>/<<<  Part time (Home Office)...
 Fila 215: ...Ejecutivo de Ventas  >>>/<<<  Part time (Home Office)...
------------------------------------------------------------
=== Columna 'funciones' (25 apariciones) ===
 Fila 15: ...                       - Recién egresado >>>/<<< a o Bachiller de la carrera de Ingenierí...
 Fila 16: ...producción para derivarlos al área de QA >>>/<<< QC (calidad). Visitas a plantas de los c...
 Fila 21: ... a los requerimientos técnicos exigidos  >>>/<<<  Realizar los servicios de inspección té...
 Fila 23: ...                       - Recién egresado >>>/<<< a o Bachiller de la carrera de Ingenierí...
 Fila 32: ...2- Programar PLC >>>/<<< HMI >>>/<<< SCADA, configurar Accionamientos (VF...
------------------------------------------------------------
=== Columna 'conocimientos' (18 apariciones) ===
 Fila 6: ...a:1:{i:0;s:231:"Bachiller o titulado >>>/<<< a de las carreras de Ingeniería mecánica...
 Fila 7: ...ra viajar(indispensable). Programación C >>>/<<< C++(Deseable). Conocimiento de librerías...
 Fila 8: ...ra viajar(indispensable). Programación C >>>/<<< C++(Deseable). Conocimiento de librerías...
 Fila 11: ... Outlook y Office - Intermedio Autocad y >>>/<<< o programas similares - Avanzado Conocim...
 Fila 21: ...-Estudios técnicos en ingeniería  >>>/<<<  técnico mecánico -Experiencia: 02 años ...
------------------------------------------------------------
=== Columna 'experiencia' (1 apariciones) ===
 Fila 58: ...a:1:{i:0;s:189:"Profesional bachiller >>>/<<< titulado de Ingeniería Mecánica, Mecatró...
------------------------------------------------------------
=== Columna 'experiencia_cv' (13 apariciones) ===
 Fila 8: ...uras avanzadas usando NI LabVIEW ||| Git >>>/<<< Github ||| INGLÉS ||| INNOVACIÓN Y CREAT...
 Fila 9: ... AutoCAD ||| Autodesk AutoCAD Electrical >>>/<<<  Plant 3D ||| Autodesk Fusion ||| Autode...
 Fila 40: ...ACIÓN ||| Power BI ||| Programacion en C >>>/<<< C++ ||| Python ||| SQL ||| TOMA DE DECIS...
 Fila 63: ...|| POWER BI ||| Python ||| SAP ||| SAP S >>>/<<< 4HANA PM VERSIO'N 2022 MANTENIMIENTO DE ...
 Fila 67: ...zación en Gestión por Procesos ||| SAP S >>>/<<< 4HANA INTEGRAL (MM, PP, SD, FI) ||| Tabl...
------------------------------------------------------------
=== Columna 'estudios_cv' (2 apariciones) ===
 Fila 63: ...sión y transformadores de potencia (ANSI >>>/<<< IEEE C37.91) ||| Centrales Hidroeléctric...
 Fila 68: ...gramación de PLCs AllenBradley-Rockwell  >>>/<<< Sistemas SCADA ||| Programación HMI en e...
------------------------------------------------------------

In [37]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['-', '+', '(', ')']
 -> Columna 'funciones': ['-', ':', '{', ';', '"', '|', '}', '(', '+', ')', '>', '&']
 -> Columna 'conocimientos': ['(', ')', '*', '&', ':', '{', ';', '"', '|', '}', '+', '-', '@']
 -> Columna 'experiencia': ['=', ';', '(', ')', ':', '{', '"', '}', '+']
 -> Columna 'experiencia_cv': ['|', ':', '-', '"', '(', ')', '&', '+', '#', "'", ';', '_', '°', ']']
 -> Columna 'estudios_cv': ['|', '-', ':', ';', '+', '&', '(', ')', '"']

In [38]:
inspeccionar_contexto(df_final, '@', columnas_texto)

Buscando el carácter: '@'

=== Columna 'conocimientos' (1 apariciones) ===
 Fila 105: ...PERFIL REQUERIDO: Egresad >>>@<<<  de las carreras de Ingeniería Industria...
------------------------------------------------------------

In [39]:
diccionario_hallazgos = {
    '@': 'o/a'
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['conocimientos']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [40]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['-', '+', '(', ')']
 -> Columna 'funciones': ['-', ':', '{', ';', '"', '|', '}', '(', '+', ')', '>', '&']
 -> Columna 'conocimientos': ['(', ')', '*', '&', ':', '{', ';', '"', '|', '}', '+', '-']
 -> Columna 'experiencia': ['=', ';', '(', ')', ':', '{', '"', '}', '+']
 -> Columna 'experiencia_cv': ['|', ':', '-', '"', '(', ')', '&', '+', '#', "'", ';', '_', '°', ']']
 -> Columna 'estudios_cv': ['|', '-', ':', ';', '+', '&', '(', ')', '"']

In [41]:
inspeccionar_contexto(df_final, '&', columnas_texto)

Buscando el carácter: '&'

=== Columna 'funciones' (2 apariciones) ===
 Fila 32: ...Diseñar planos de tableros de control, P >>>&<<< ID, unifilares, layout, ruteo, etc. ...
 Fila 70: ...lanta de tratamiento en el rubro de Oil  >>>&<<<  Gas (tuberías, válvulas, equipos, instr...
------------------------------------------------------------
=== Columna 'conocimientos' (4 apariciones) ===
 Fila 1: ...omo ingeniero de DISEÑO en el sector oil >>>&<<< gas (excluyente) * Experiencia en config...
 Fila 5: ...riencia mínima 0 a 01 años en sector oil >>>&<<< gas.   Conocimientos de desarrollo de di...
 Fila 49: ...omo ingeniero de DISEÑO en el sector oil >>>&<<< gas (excluyente) * Experiencia en config...
 Fila 70: ...riencia mínima 0 a 01 años en sector oil >>>&<<< gas.   Conocimientos de desarrollo de di...
------------------------------------------------------------
=== Columna 'experiencia_cv' (2 apariciones) ===
 Fila 8: ...E RELACIONES INTERPERSONALES ||| Matlab  >>>&<<<  Simulink, LabVIEW, MPlab ||| ORGANIZACI...
 Fila 116: ...DE RELACIONES INTERPERSONALES ||| Matlab >>>&<<< Simulink ||| Microsoft Office  (Word, Ex...
------------------------------------------------------------
=== Columna 'estudios_cv' (1 apariciones) ===
 Fila 32: ... ||| Interpretación de planos P >>>&<<< ID , configuración de instrumentos de me...
------------------------------------------------------------

In [44]:
diccionario_hallazgos = {
    '&': 'y'
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['funciones','conocimientos','experiencia_cv','estudios_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [45]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['-', '+', '(', ')']
 -> Columna 'funciones': ['-', ':', '{', ';', '"', '|', '}', '(', '+', ')', '>']
 -> Columna 'conocimientos': ['(', ')', '*', ':', '{', ';', '"', '|', '}', '+', '-']
 -> Columna 'experiencia': ['=', ';', '(', ')', ':', '{', '"', '}', '+']
 -> Columna 'experiencia_cv': ['|', ':', '-', '"', '(', ')', '+', '#', "'", ';', '_', '°', ']']
 -> Columna 'estudios_cv': ['|', '-', ':', ';', '+', '(', ')', '"']

In [46]:
inspeccionar_contexto(df_final, '#', columnas_texto)

Buscando el carácter: '#'

=== Columna 'experiencia_cv' (1 apariciones) ===
 Fila 36: ...ACIÓN ||| Power BI ||| Programación en C >>>#<<<  y C++ ||| Python ||| TOMA DE DECISIONES...
------------------------------------------------------------

In [47]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/\#]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['-', '+', '(', ')']
 -> Columna 'funciones': ['-', ':', '{', ';', '"', '|', '}', '(', '+', ')', '>']
 -> Columna 'conocimientos': ['(', ')', '*', ':', '{', ';', '"', '|', '}', '+', '-']
 -> Columna 'experiencia': ['=', ';', '(', ')', ':', '{', '"', '}', '+']
 -> Columna 'experiencia_cv': ['|', ':', '-', '"', '(', ')', '+', "'", ';', '_', '°', ']']
 -> Columna 'estudios_cv': ['|', '-', ':', ';', '+', '(', ')', '"']

In [48]:
inspeccionar_contexto(df_final, '>', columnas_texto)

Buscando el carácter: '>'

=== Columna 'funciones' (1 apariciones) ===
 Fila 29: ...trabajos a grandes alturas geográficas ( >>>><<< 4000msnm), cuando se requiera....
------------------------------------------------------------

In [49]:
diccionario_hallazgos = {
    '>': ' mayor a '
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['funciones']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [50]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/\#]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['-', '+', '(', ')']
 -> Columna 'funciones': ['-', ':', '{', ';', '"', '|', '}', '(', '+', ')']
 -> Columna 'conocimientos': ['(', ')', '*', ':', '{', ';', '"', '|', '}', '+', '-']
 -> Columna 'experiencia': ['=', ';', '(', ')', ':', '{', '"', '}', '+']
 -> Columna 'experiencia_cv': ['|', ':', '-', '"', '(', ')', '+', "'", ';', '_', '°', ']']
 -> Columna 'estudios_cv': ['|', '-', ':', ';', '+', '(', ')', '"']

In [51]:
inspeccionar_contexto(df_final, '°', columnas_texto)

Buscando el carácter: '°'

=== Columna 'experiencia_cv' (2 apariciones) ===
 Fila 170: ...ertificación empresarial de "COFIDE"  22 >>>°<<<  TABLA DE NEGOCIOS MYPE 09 de febrero al...
 Fila 176: ... ||| Ayudantía en el laboratorio N >>>°<<< 21 de la Facultad de Ingeniería Química ...
------------------------------------------------------------

In [52]:
diccionario_hallazgos = {
    'N°': ' Número '
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['experiencia_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [53]:
print("Resultado en la fila 170:")
print(df_final.loc[170, 'experiencia_cv'])

Resultado en la fila 170:
 ||| Autocad ||| Egresado de la Facultad de Ingeniería Química de la Universidad Nacional de Ingeniería.     Soy un joven dinámico, estratégico, emprendedor, con amplio desenvolvimiento y alta comunicación a todo nivel, responsable, gusta trabajar en grupo, con ganas de tener un buen desarrollo profesional, buen manejo y dominio de trabajo bajo presión, con aptitudes en liderar equipos de trabajo, mente innovadora, con facilidad para tomar decisiones y enfrentar situaciones de desafío que un mundo cada día más competitivo te exige. ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| Lenguaje de Programación C++  ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Me gusta hacer muchas actividades tales como practicar TAEK WONDO, NATACIÓN, FÚTBOL y en mis ratos libres suelo mucho LEER ||| Microsoft Excel ||| ORGANIZACIÓN ||| PORTUGUÉS ||| Programa de certificación empresarial de "COFIDE"  22° TABLA DE NEGOCIOS MYPE 09 de febrero al 30 de abril del 2015, Lima ||| RU

In [54]:
diccionario_hallazgos = {
    '22°': ' 22 edición '
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['experiencia_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [55]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/\#]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['-', '+', '(', ')']
 -> Columna 'funciones': ['-', ':', '{', ';', '"', '|', '}', '(', '+', ')']
 -> Columna 'conocimientos': ['(', ')', '*', ':', '{', ';', '"', '|', '}', '+', '-']
 -> Columna 'experiencia': ['=', ';', '(', ')', ':', '{', '"', '}', '+']
 -> Columna 'experiencia_cv': ['|', ':', '-', '"', '(', ')', '+', "'", ';', '_', ']']
 -> Columna 'estudios_cv': ['|', '-', ':', ';', '+', '(', ')', '"']

In [56]:
inspeccionar_contexto(df_final, '+', columnas_texto)

Buscando el carácter: '+'

=== Columna 'cargo' (3 apariciones) ===
 Fila 30: ...ctica Profesional Ingeniería en Centro I >>>+<<< D en empresa Tecnológica...
 Fila 38: ...ctica Profesional Ingeniería en Centro I >>>+<<< D en empresa Tecnológica...
 Fila 96: ...ctica Profesional Ingeniería en Centro I >>>+<<< D en empresa Tecnológica...
------------------------------------------------------------
=== Columna 'funciones' (7 apariciones) ===
 Fila 7: ...ctura de la solución a implementar (IoT  >>>+<<<  IA). -Participar en la construcción de ...
 Fila 8: ...ctura de la solución a implementar (IoT  >>>+<<<  IA). -Participar en la construcción de ...
 Fila 16: ...ura de Planta.Dar soporte al equipo de I >>>+<<< D >>>+<<< i en proyectos en proceso o nuevos des...
 Fila 30: ...ación comercial y científica, mediante I >>>+<<< D.  Deseable (no excluyente): Entender l...
 Fila 38: ...ación comercial y científica, mediante I >>>+<<< D.  Deseable (no excluyente): Entender l...
------------------------------------------------------------
=== Columna 'conocimientos' (4 apariciones) ===
 Fila 7: ... viajar(indispensable). Programación C/C >>>+<<<  >>>+<<< (Deseable). Conocimiento de librerías o...
 Fila 8: ... viajar(indispensable). Programación C/C >>>+<<<  >>>+<<< (Deseable). Conocimiento de librerías o...
 Fila 80: ... viajar(indispensable). Programación C/C >>>+<<<  >>>+<<< (Deseable). Conocimiento de librerías o...
 Fila 152: ...Buen conocimiento de Programación en: C >>>+<<<  >>>+<<< , Algoritmos Avanzados y Matematicas...
------------------------------------------------------------
=== Columna 'experiencia' (1 apariciones) ===
 Fila 21: ... >>>+<<< 1 año en sector industrial, mantenimient...
------------------------------------------------------------
=== Columna 'experiencia_cv' (36 apariciones) ===
 Fila 8: ...Plab ||| ORGANIZACIÓN ||| Programación C >>>+<<<  >>>+<<<  ||| Programación de PLCs (Siemens S7 1...
 Fila 10: ... ||| Java ||| Lenguaje de Programacion C >>>+<<<  >>>+<<<   ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ...
 Fila 13: ...C >>>+<<<  >>>+<<<  ||| ESPAÑOL ||| INGLÉS ||| INNOVACIÓN ...
 Fila 19: ...| BICSI CALA ICT  SUMMIT PERÚ 2026 ||| C >>>+<<<  >>>+<<<  ||| Code Composer ||| Comunicación Asi...
 Fila 21: ...| BICSI CALA ICT  SUMMIT PERÚ 2026 ||| C >>>+<<<  >>>+<<<  ||| Code Composer ||| Comunicación Asi...
------------------------------------------------------------
=== Columna 'estudios_cv' (3 apariciones) ===
 Fila 26: ...de programación orientada a objetos en C >>>+<<<  >>>+<<< . ||| Desarrollo de programas utilizand...
 Fila 46: ...as, funciones avanzadas (BUSCARV, INDICE >>>+<<< COINCIDIR, etc.) y herramientas de valid...
 Fila 174: ... básico de lenguaje de programación en C >>>+<<<  >>>+<<<  y Java. ||| Conocimiento básico de sim...
------------------------------------------------------------

In [58]:
inspeccionar_contexto(df_final, '-', columnas_texto)

Buscando el carácter: '-'

=== Columna 'cargo' (30 apariciones) ===
 Fila 16: ...Asistente de Proyectos CAD >>>-<<< CAM...
 Fila 18: ...Asistente de Producción  >>>-<<<  Rubro manufactura...
 Fila 24: ...INGENIERO DE PRODUCCIÓN  >>>-<<<  RUBRO MANUFACTURA...
 Fila 25: ...Asistente de Producción  >>>-<<<  Rubro manufactura...
 Fila 31: ...Asistente de Producción  >>>-<<<  Rubro manufactura...
------------------------------------------------------------
=== Columna 'funciones' (74 apariciones) ===
 Fila 3: ...resentaciones de las propuestas técnicas >>>-<<< comerciales a los Ingenieros de Ventas. ...
 Fila 7: ... >>>-<<< Participar en la documentación del diseñ...
 Fila 8: ... >>>-<<< Participar en la documentación del diseñ...
 Fila 9: ... >>>-<<<  Asegurar la ejecución de las actividade...
 Fila 12: ... >>>-<<<  Promocionar los productos y servicios  >>>-<<< ...
------------------------------------------------------------
=== Columna 'conocimientos' (50 apariciones) ===
 Fila 9: ... >>>-<<<  Bachiller de las carreras de Ing. Mecán...
 Fila 11: ...Conocimientos Outlook y Office  >>>-<<<  Intermedio Autocad y/o programas simila...
 Fila 12: ... >>>-<<<  Estudios en Ingeniería o carreras afine...
 Fila 13: ... >>>-<<<  Bachiller o titulado en Ingeniería mecá...
 Fila 17: ... >>>-<<<  Bachiller o titulado en Ingeniería mecá...
------------------------------------------------------------
=== Columna 'experiencia_cv' (75 apariciones) ===
 Fila 1: ...ación y creatividad, Iniciativa ||| IBM  >>>-<<<  Maximo Asset Management ||| INGLÉS ||| ...
 Fila 2: ...mas claves de Automatización Industrial  >>>-<<<  Webinar Week 2023 ||| INGLÉS ||| INNOVA...
 Fila 8: ...|| Programación de PLCs (Siemens S7 1200 >>>-<<< S7 1500) ||| Programación Python  ||| Pr...
 Fila 9: ...o ||| ORGANIZACIÓN ||| Outlook ||| PCAP  >>>-<<<  Programming Essentials in Python ||| PO...
 Fila 11: ...ERIOR DE LA FACULTAD DE INGENIERIA CIVIL >>>-<<<  UNI ||| TOMA DE DECISIONES ||| TRABAJO ...
------------------------------------------------------------
=== Columna 'estudios_cv' (29 apariciones) ===
 Fila 3: ...ntas de Oxigeno medicinal. ||| Inventor  >>>-<<<  Nivel Avanzado...
 Fila 9: ..., manage, and prepare reliable analytics >>>-<<< ready dat...
 Fila 12: ...Avanzado ||| Basico >>>-<<< Intermedio ||| Intermedio...
 Fila 16: ...instalación de variadores de velocidad.  >>>-<<<  Configuración de usuario y variador >>>-<<< mot...
 Fila 23: ... ||| Aplicaciones teórico >>>-<<< prácticas relacionadas con el estudio de...
------------------------------------------------------------

In [59]:
print("Resultado en la fila 12:")
print(df_final.loc[12, 'conocimientos'])

Resultado en la fila 12:
- Estudios en Ingeniería o carreras afines. - Experiencia: 02 años en puestos similares   Disponibilidad laboral Inmediata a tiempo completo. - Conocimientos en: AutoCAD, lectura de planos, Office a nivel intermedio. - Conocimiento de sistemas de bombeo de agua para uso doméstico y de uso industrial.(deseable) - Conocimiento de hidráulica. - Conocimiento de técnicas de venta - Tener Brevete A1

In [60]:
for col in ['funciones', 'conocimientos', 'estudios_cv']:
    # Esto busca guiones al inicio o precedidos por espacio/separador y les añade un espacio si no lo tienen
    df_final[col] = df_final[col].str.replace(r'(^|[\s])\-([a-zA-Záéíóú])', r'\1- \2', regex=True)

In [61]:
inspeccionar_contexto(df_final, '-', columnas_texto)

Buscando el carácter: '-'

=== Columna 'cargo' (30 apariciones) ===
 Fila 16: ...Asistente de Proyectos CAD >>>-<<< CAM...
 Fila 18: ...Asistente de Producción  >>>-<<<  Rubro manufactura...
 Fila 24: ...INGENIERO DE PRODUCCIÓN  >>>-<<<  RUBRO MANUFACTURA...
 Fila 25: ...Asistente de Producción  >>>-<<<  Rubro manufactura...
 Fila 31: ...Asistente de Producción  >>>-<<<  Rubro manufactura...
------------------------------------------------------------
=== Columna 'funciones' (74 apariciones) ===
 Fila 3: ...resentaciones de las propuestas técnicas >>>-<<< comerciales a los Ingenieros de Ventas. ...
 Fila 7: ... >>>-<<<  Participar en la documentación del dise...
 Fila 8: ... >>>-<<<  Participar en la documentación del dise...
 Fila 9: ... >>>-<<<  Asegurar la ejecución de las actividade...
 Fila 12: ... >>>-<<<  Promocionar los productos y servicios  >>>-<<< ...
------------------------------------------------------------
=== Columna 'conocimientos' (50 apariciones) ===
 Fila 9: ... >>>-<<<  Bachiller de las carreras de Ing. Mecán...
 Fila 11: ...Conocimientos Outlook y Office  >>>-<<<  Intermedio Autocad y/o programas simila...
 Fila 12: ... >>>-<<<  Estudios en Ingeniería o carreras afine...
 Fila 13: ... >>>-<<<  Bachiller o titulado en Ingeniería mecá...
 Fila 17: ... >>>-<<<  Bachiller o titulado en Ingeniería mecá...
------------------------------------------------------------
=== Columna 'experiencia_cv' (75 apariciones) ===
 Fila 1: ...ación y creatividad, Iniciativa ||| IBM  >>>-<<<  Maximo Asset Management ||| INGLÉS ||| ...
 Fila 2: ...mas claves de Automatización Industrial  >>>-<<<  Webinar Week 2023 ||| INGLÉS ||| INNOVA...
 Fila 8: ...|| Programación de PLCs (Siemens S7 1200 >>>-<<< S7 1500) ||| Programación Python  ||| Pr...
 Fila 9: ...o ||| ORGANIZACIÓN ||| Outlook ||| PCAP  >>>-<<<  Programming Essentials in Python ||| PO...
 Fila 11: ...ERIOR DE LA FACULTAD DE INGENIERIA CIVIL >>>-<<<  UNI ||| TOMA DE DECISIONES ||| TRABAJO ...
------------------------------------------------------------
=== Columna 'estudios_cv' (29 apariciones) ===
 Fila 3: ...ntas de Oxigeno medicinal. ||| Inventor  >>>-<<<  Nivel Avanzado...
 Fila 9: ..., manage, and prepare reliable analytics >>>-<<< ready dat...
 Fila 12: ...Avanzado ||| Basico >>>-<<< Intermedio ||| Intermedio...
 Fila 16: ...instalación de variadores de velocidad.  >>>-<<<  Configuración de usuario y variador >>>-<<< mot...
 Fila 23: ... ||| Aplicaciones teórico >>>-<<< prácticas relacionadas con el estudio de...
------------------------------------------------------------

In [62]:
print("Resultado en la fila 12:")
print(df_final.loc[12, 'conocimientos'])

Resultado en la fila 12:
- Estudios en Ingeniería o carreras afines. - Experiencia: 02 años en puestos similares   Disponibilidad laboral Inmediata a tiempo completo. - Conocimientos en: AutoCAD, lectura de planos, Office a nivel intermedio. - Conocimiento de sistemas de bombeo de agua para uso doméstico y de uso industrial.(deseable) - Conocimiento de hidráulica. - Conocimiento de técnicas de venta - Tener Brevete A1

In [64]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/\#\-\+]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['(', ')']
 -> Columna 'funciones': [':', '{', ';', '"', '|', '}', '(', ')']
 -> Columna 'conocimientos': ['(', ')', '*', ':', '{', ';', '"', '|', '}']
 -> Columna 'experiencia': ['=', ';', '(', ')', ':', '{', '"', '}']
 -> Columna 'experiencia_cv': ['|', ':', '"', '(', ')', "'", ';', '_', ']']
 -> Columna 'estudios_cv': ['|', ':', ';', '(', ')', '"']

In [65]:
inspeccionar_contexto(df_final, '=', columnas_texto)

Buscando el carácter: '='

=== Columna 'experiencia' (2 apariciones) ===
 Fila 1: ...Junior  >>>=<<<  mínimo 03 años en ingeniería de diseño....
 Fila 49: ...Junior  >>>=<<<  mínimo 03 años en ingeniería de diseño....
------------------------------------------------------------

In [66]:
diccionario_hallazgos = {
    '=': ''
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['experiencia']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [67]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/\#\-\+]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['(', ')']
 -> Columna 'funciones': [':', '{', ';', '"', '|', '}', '(', ')']
 -> Columna 'conocimientos': ['(', ')', '*', ':', '{', ';', '"', '|', '}']
 -> Columna 'experiencia': [';', '(', ')', ':', '{', '"', '}']
 -> Columna 'experiencia_cv': ['|', ':', '"', '(', ')', "'", ';', '_', ']']
 -> Columna 'estudios_cv': ['|', ':', ';', '(', ')', '"']

In [68]:
inspeccionar_contexto(df_final, '_', columnas_texto)

Buscando el carácter: '_'

=== Columna 'experiencia_cv' (1 apariciones) ===
 Fila 107: ...AutoCAD ||| CADe >>>_<<< SIMU ||| Excel ||| Excel con Macros ||| ...
------------------------------------------------------------

In [71]:
diccionario_hallazgos = {
    '_': ''
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['experiencia_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [72]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/\#\-\+]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['(', ')']
 -> Columna 'funciones': [':', '{', ';', '"', '|', '}', '(', ')']
 -> Columna 'conocimientos': ['(', ')', '*', ':', '{', ';', '"', '|', '}']
 -> Columna 'experiencia': [';', '(', ')', ':', '{', '"', '}']
 -> Columna 'experiencia_cv': ['|', ':', '"', '(', ')', "'", ';', ']']
 -> Columna 'estudios_cv': ['|', ':', ';', '(', ')', '"']

In [73]:
inspeccionar_contexto(df_final, ';', columnas_texto)

Buscando el carácter: ';'

=== Columna 'funciones' (28 apariciones) ===
 Fila 6: ...a:1:{i:0 >>>;<<< s:393:" Cumplir con el programa de mante...
 Fila 16: ...s expedientes técnicos de los proyectos. >>>;<<< 1Verificar que los mecanizados y trabajo...
 Fila 18: ...a:1:{i:0 >>>;<<< s:404:"Apoyar en la elaboración y seguim...
 Fila 20: ...a:1:{i:0 >>>;<<< s:481:"Cumplir con el programa de manten...
 Fila 26: ...a:3:{i:0 >>>;<<< s:178:"Configurar, calibrar y ajustar se...
------------------------------------------------------------
=== Columna 'conocimientos' (19 apariciones) ===
 Fila 6: ...a:1:{i:0 >>>;<<< s:231:"Bachiller o titulado/a de las car...
 Fila 18: ...a:1:{i:0 >>>;<<< s:38:"Excel nivel intermedio (Indispensa...
 Fila 20: ...a:1:{i:0 >>>;<<< s:31:"Office nivel avanzado y Autocad" >>>;<<< }...
 Fila 26: ...a:4:{i:0 >>>;<<< s:31:"- Dominio de Python intermedio " >>>;<<< i...
 Fila 28: ...a:1:{i:0 >>>;<<< s:31:"Office nivel avanzado y Autocad" >>>;<<< }...
------------------------------------------------------------
=== Columna 'experiencia' (19 apariciones) ===
 Fila 6: ...N >>>;<<< ...
 Fila 18: ...a:1:{i:0 >>>;<<< s:100:"Experiencia mínima de 01 año en e...
 Fila 20: ...a:1:{i:0 >>>;<<< s:206:"Experiencia previa en plantas man...
 Fila 26: ...N >>>;<<< ...
 Fila 28: ...a:1:{i:0 >>>;<<< s:206:"Experiencia previa en plantas man...
------------------------------------------------------------
=== Columna 'experiencia_cv' (6 apariciones) ===
 Fila 63: ...SONALES ||| MS Office (Word, Power Point >>>;<<<  Excel) ||| ORGANIZACIÓN ||| PLC 1 ||| P...
 Fila 126: ...de Gestión de la Calidad, ISO 9001:20015 >>>;<<<   ISO 14001:2015 >>>;<<<  OHSAS 18001:2007 >>>;<<<   SA ...
 Fila 137: ...mientos Operativos de Planta de Procesos >>>;<<<  Planta de Emulsiones >>>;<<<  Planta de MAC, Pl...
 Fila 142: ...emás, con un nivel alto de ética y moral >>>;<<<  me encanta trabajar en equipo, asumir n...
 Fila 174: ...s. Certificada como Green Belt Six Sigma >>>;<<<  auditor interno de ISO 9001, ISO 14001,...
------------------------------------------------------------
=== Columna 'estudios_cv' (4 apariciones) ===
 Fila 25: ...ca de estos para la ejecución de pruebas >>>;<<<  así como, la confiabilidad para realiza...
 Fila 143: ... de Proyectos bajo el enfoque del PMBOK  >>>;<<< Evaluacion Financiera de Proyectos >>>;<<< Herra...
 Fila 195: ... de Proyectos bajo el enfoque del PMBOK  >>>;<<< Evaluacion Financiera de Proyectos >>>;<<< Herra...
 Fila 208: ... de Proyectos bajo el enfoque del PMBOK  >>>;<<< Evaluacion Financiera de Proyectos >>>;<<< Herra...
------------------------------------------------------------

In [74]:
print("Resultado en la fila 6:")
print(df_final.loc[6, 'funciones'])

Resultado en la fila 6:
a:1:{i:0;s:393:" Cumplir con el programa de mantenimiento preventivo y correctivo | Supervisar e inspeccionar la planta para asegurar el buen funcionamiento de las máquinas en general | Supervisar la ejecución de los trabajos de mantenimiento correctivo y preventivo de la planta | Mantener registros precisos de mantenimiento, informes de incidentes y mejoras implementadas | Control del personal a cargo.";}

In [75]:
# Diccionario con patrones Regex para destruir la estructura PHP sin tocar tu texto
diccionario_php = {
    r'a:\d+:\{': '',      # Borra el inicio del array (ej. a:1:{ o a:3:{)
    r'i:\d+;': '',        # Borra los índices de lista (ej. i:0;)
    r's:\d+:"': '',       # Borra el marcador de texto y tamaño (ej. s:393:")
    r'";\}': '',          # Borra el cierre final del array
    r'";': ' ',           # Borra el cierre entre elementos de la lista
    r'N;': ''             # Borra los valores nulos de PHP (N;)
}

print("Limpiando formato de PHP Serializado.\n")

columnas_php = ['funciones', 'conocimientos', 'experiencia']

for col in columnas_php:
    if df_final[col].dtype == 'object':
        for mal, bien in diccionario_php.items():
            # regex=True es obligatorio aquí porque estamos usando patrones dinámicos (\d+)
            df_final[col] = df_final[col].str.replace(mal, bien, regex=True)

print("Resultado limpio en la fila 6 de 'funciones':")
print(df_final.loc[6, 'funciones'])

Limpiando formato de PHP Serializado.

Resultado limpio en la fila 6 de 'funciones':
 Cumplir con el programa de mantenimiento preventivo y correctivo | Supervisar e inspeccionar la planta para asegurar el buen funcionamiento de las máquinas en general | Supervisar la ejecución de los trabajos de mantenimiento correctivo y preventivo de la planta | Mantener registros precisos de mantenimiento, informes de incidentes y mejoras implementadas | Control del personal a cargo.

In [76]:
inspeccionar_contexto(df_final, ';', columnas_texto)

Buscando el carácter: ';'

=== Columna 'funciones' (9 apariciones) ===
 Fila 16: ...s expedientes técnicos de los proyectos. >>>;<<< 1Verificar que los mecanizados y trabajo...
 Fila 27: ... de presupuesto y memorias descriptivas. >>>;<<< s:53:Revisar las solicitudes de obra en ...
 Fila 51: ... de presupuesto y memorias descriptivas. >>>;<<< s:53:Revisar las solicitudes de obra en ...
 Fila 62: ...conforme a los procedimientos definidos. >>>;<<< s:84:- Elaborar informes técnicos y de c...
 Fila 74: ...s en coordinación con el ing. de ventas. >>>;<<< s:87:Coordinar el supervisor de operacio...
------------------------------------------------------------
=== Columna 'experiencia_cv' (6 apariciones) ===
 Fila 63: ...SONALES ||| MS Office (Word, Power Point >>>;<<<  Excel) ||| ORGANIZACIÓN ||| PLC 1 ||| P...
 Fila 126: ...de Gestión de la Calidad, ISO 9001:20015 >>>;<<<   ISO 14001:2015 >>>;<<<  OHSAS 18001:2007 >>>;<<<   SA ...
 Fila 137: ...mientos Operativos de Planta de Procesos >>>;<<<  Planta de Emulsiones >>>;<<<  Planta de MAC, Pl...
 Fila 142: ...emás, con un nivel alto de ética y moral >>>;<<<  me encanta trabajar en equipo, asumir n...
 Fila 174: ...s. Certificada como Green Belt Six Sigma >>>;<<<  auditor interno de ISO 9001, ISO 14001,...
------------------------------------------------------------
=== Columna 'estudios_cv' (4 apariciones) ===
 Fila 25: ...ca de estos para la ejecución de pruebas >>>;<<<  así como, la confiabilidad para realiza...
 Fila 143: ... de Proyectos bajo el enfoque del PMBOK  >>>;<<< Evaluacion Financiera de Proyectos >>>;<<< Herra...
 Fila 195: ... de Proyectos bajo el enfoque del PMBOK  >>>;<<< Evaluacion Financiera de Proyectos >>>;<<< Herra...
 Fila 208: ... de Proyectos bajo el enfoque del PMBOK  >>>;<<< Evaluacion Financiera de Proyectos >>>;<<< Herra...
------------------------------------------------------------

In [77]:
diccionario_hallazgos = {
    ';': ','
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['experiencia_cv','estudios_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [84]:
inspeccionar_contexto(df_final, ';s:', columnas_texto)

Buscando el carácter: ';s:'

=== Columna 'funciones' (8 apariciones) ===
 Fila 27: ... de presupuesto y memorias descriptivas. >>>;s:<<< 53:Revisar las solicitudes de obra en el...
 Fila 51: ... de presupuesto y memorias descriptivas. >>>;s:<<< 53:Revisar las solicitudes de obra en el...
 Fila 62: ...conforme a los procedimientos definidos. >>>;s:<<< 84:- Elaborar informes técnicos y de cal...
 Fila 74: ...s en coordinación con el ing. de ventas. >>>;s:<<< 87:Coordinar el supervisor de operacione...
 Fila 76: ... de presupuesto y memorias descriptivas. >>>;s:<<< 53:Revisar las solicitudes de obra en el...
------------------------------------------------------------

In [83]:
print("Resultado en la fila 27:")
print(df_final.loc[27, 'funciones'])

Resultado en la fila 27:
Recopilar información referente a producción en campo . Elaborar dibujos de AutoCAD de los proyectos según la necesidad. Cumplir todas las políticas, normas, procedimientos y reglamentos existentes para la seguridad de todo el personal, máquinas, equipos, materiales y áreas de trabajo. Elaborar cuadros estadísticos de costos según el Jefe de producción..  Elaboración de presupuesto y memorias descriptivas.;s:53:Revisar las solicitudes de obra en el correo de obras;s:16:Elabora informes

In [87]:
# Patrón para atrapar la variante de PHP sin comillas
patron_zombie_php = r';s:\d+:'

print("Eliminando variante de PHP serializado.\n")

for col in ['funciones']:
    if df_final[col].dtype == 'object':
        df_final[col] = df_final[col].str.replace(patron_zombie_php, ' ', regex=True)

print("Resultado limpio en la fila 27:")
print(df_final.loc[27, 'funciones'])

Eliminando variante de PHP serializado.

Resultado limpio en la fila 27:
Recopilar información referente a producción en campo . Elaborar dibujos de AutoCAD de los proyectos según la necesidad. Cumplir todas las políticas, normas, procedimientos y reglamentos existentes para la seguridad de todo el personal, máquinas, equipos, materiales y áreas de trabajo. Elaborar cuadros estadísticos de costos según el Jefe de producción..  Elaboración de presupuesto y memorias descriptivas. Revisar las solicitudes de obra en el correo de obras Elabora informes

In [88]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/\#\-\+]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['(', ')']
 -> Columna 'funciones': ['|', '(', ')', ':', ';']
 -> Columna 'conocimientos': ['(', ')', '*', '|', ':']
 -> Columna 'experiencia': ['(', ')']
 -> Columna 'experiencia_cv': ['|', ':', '"', '(', ')', "'", ']']
 -> Columna 'estudios_cv': ['|', ':', '(', ')', '"']

In [92]:
inspeccionar_contexto(df_final, ';', columnas_texto)

Buscando el carácter: ';'

=== Columna 'funciones' (2 apariciones) ===
 Fila 16: ...s expedientes técnicos de los proyectos. >>>;<<< 1Verificar que los mecanizados y trabajo...
 Fila 82: ...estándares de los trabajos programados.  >>>;<<< 1 Realizar informes de reconocimiento y ...
------------------------------------------------------------

In [93]:
print("Resultado en la fila 82:")
print(df_final.loc[82, 'funciones'])

Resultado en la fila 82:
 Implementar, supervisar y fiscalizar el Sistema de Seguridad y Salud en el Trabajo. .  Sostener reuniones con el equipo, para capacitar, reforzar, revisar el cumplimiento de gestión de seguridad, Salud Ocupacional y medio ambiente .  Supervisar el cumplimiento de las indicaciones sobre Seguridad y Salud en el Trabajo, que se le da a los trabajadores.  Llevar el control y seguimiento de Accidentes Laborales.  Validar los riesgos subestándares de los trabajos programados. ;1 Realizar informes de reconocimiento y evaluación de accidentes, enfermedades profesionales, condiciones y actos inseguros.   Armar las diferentes brigadas y capacitar a los brigadistas. ;s: Asistir al Coordinador SSOMA.  Entre otras.

In [94]:
inspeccionar_contexto(df_final, ';s:', columnas_texto)

Buscando el carácter: ';s:'

=== Columna 'funciones' (1 apariciones) ===
 Fila 82: ...brigadas y capacitar a los brigadistas.  >>>;s:<<<  Asistir al Coordinador SSOMA.  Entre ot...
------------------------------------------------------------

In [95]:
diccionario_hallazgos = {
    ';s:': '',
    ';1': ''
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['funciones']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [96]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/\#\-\+]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['(', ')']
 -> Columna 'funciones': ['|', '(', ')', ':']
 -> Columna 'conocimientos': ['(', ')', '*', '|', ':']
 -> Columna 'experiencia': ['(', ')']
 -> Columna 'experiencia_cv': ['|', ':', '"', '(', ')', "'", ']']
 -> Columna 'estudios_cv': ['|', ':', '(', ')', '"']

In [97]:
inspeccionar_contexto(df_final, ':', columnas_texto)

Buscando el carácter: ':'

=== Columna 'funciones' (27 apariciones) ===
 Fila 14: ...FUNCIONES >>>:<<<  - Asegurar la ejecución de las activida...
 Fila 15: ...eniería.. Experiencia y otros requisitos >>>:<<<                                         ...
 Fila 19: ...FUNCIONES >>>:<<<  - Asegurar la ejecución de las activida...
 Fila 23: ...eniería.. Experiencia y otros requisitos >>>:<<<                                         ...
 Fila 25: ...REQUISITOS >>>:<<<  - Profesional de las carreras universit...
------------------------------------------------------------
=== Columna 'conocimientos' (21 apariciones) ===
 Fila 12: ...eniería o carreras afines. - Experiencia >>>:<<<  02 años en puestos similares   Disponib...
 Fila 16: ...cánico paramñetrico (Inventor). Opcional >>>:<<<   Conocimiento de Nastran y modelamiento...
 Fila 21: ...eniería / técnico mecánico - Experiencia >>>:<<<  02 años en actividades similares. - Lic...
 Fila 26: ...tructuras de datos y algoritmos Deseable >>>:<<<  - Conocimiento en entornos de visualiza...
 Fila 30: ...Requisitos >>>:<<<   Estudiante de 5to ciclo en adelante de...
------------------------------------------------------------
=== Columna 'experiencia_cv' (30 apariciones) ===
 Fila 1: ...dos ||| FRANCÉS ||| Habilidades sociales >>>:<<<  Empatía, Liderazgo, Interrelación con o...
 Fila 19: ... IA - Machine Learning con Python ||| IE >>>:<<<  Sistemas de barras de cobre para tabler...
 Fila 21: ... IA - Machine Learning con Python ||| IE >>>:<<<  Sistemas de barras de cobre para tabler...
 Fila 24: ... IA - Machine Learning con Python ||| IE >>>:<<<  Sistemas de barras de cobre para tabler...
 Fila 25: ...chine Lubricant Analyst, ISO Equivalency >>>:<<<  18436-4, Category I ||| Level II, Machi...
------------------------------------------------------------
=== Columna 'estudios_cv' (9 apariciones) ===
 Fila 23: ...r controladores lineales para aplicación >>>:<<<  eléctricos, mecánicos,  electromecánico...
 Fila 63: ... |||  Los módulos llevados son >>>:<<<  Excel Básico-Excel para ingeniería- S10...
 Fila 107: ... ||| Impartido por >>>:<<<  Ing. András Muñoz Díaz ||| Impartido po...
 Fila 109: ...rks ||| Programa enfocado en desarrollar >>>:<<<  Habilidades Personales, Valores, Emplea...
 Fila 115: ...gestión, con conocimiento en la trinorma >>>:<<<  ISO 9001, ISO 14001, ISO 45001. Conocim...
------------------------------------------------------------

In [98]:
inspeccionar_contexto(df_final, '*', columnas_texto)

Buscando el carácter: '*'

=== Columna 'conocimientos' (2 apariciones) ===
 Fila 1: ... >>>*<<<  Profesional titulado de las carreras de...
 Fila 49: ... >>>*<<<  Profesional titulado de las carreras de...
------------------------------------------------------------

In [100]:
print("Resultado en la fila 1:")
print(df_final.loc[1, 'conocimientos'])

Resultado en la fila 1:
* Profesional titulado de las carreras de Ing. Electrónica, Mecatrónica o afines. * Experiencia como ingeniero de DISEÑO en el sector oilygas (excluyente) * Experiencia en configuración de PLC, sistemas de control, sistemas de seguridad. * Experiencia mínima 03 años a más. * Dominio de idioma inglés comprobado.

In [101]:
diccionario_hallazgos = {
    '*': ''
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['conocimientos']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [102]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/\#\-\+\:]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['(', ')']
 -> Columna 'funciones': ['|', '(', ')']
 -> Columna 'conocimientos': ['(', ')', '|']
 -> Columna 'experiencia': ['(', ')']
 -> Columna 'experiencia_cv': ['|', '"', '(', ')', "'", ']']
 -> Columna 'estudios_cv': ['|', '(', ')', '"']

In [103]:
inspeccionar_contexto(df_final, ' | ', columnas_texto)

Buscando el carácter: ' | '

=== Columna 'funciones' (3 apariciones) ===
 Fila 6: ...de mantenimiento preventivo y correctivo >>> | <<< Supervisar e inspeccionar la planta para...
 Fila 60: ...de mantenimiento preventivo y correctivo >>> | <<< Supervisar e inspeccionar la planta para...
 Fila 88: ...de mantenimiento preventivo y correctivo >>> | <<< Supervisar e inspeccionar la planta para...
------------------------------------------------------------
=== Columna 'conocimientos' (3 apariciones) ===
 Fila 6: ... mecánica o mecatrónica (Indispensable)  >>> | <<< Experiencia laboral de 4 años mínimo en ...
 Fila 60: ... mecánica o mecatrónica (Indispensable)  >>> | <<< Experiencia laboral de 4 años mínimo en ...
 Fila 88: ... mecánica o mecatrónica (Indispensable)  >>> | <<< Experiencia laboral de 4 años mínimo en ...
------------------------------------------------------------
=== Columna 'experiencia_cv' (1 apariciones) ===
 Fila 63: ...ificación) (mayo 2021) ||| SNC - LAVALIN >>> | <<< DISEÑANDO UN MUNDO MEJOR ||| SQL ||| TOM...
------------------------------------------------------------

In [104]:
diccionario_hallazgos = {
    ' | ': '. '
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['funciones','conocimientos','experiencia_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [105]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/\#\-\+\:\|]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['(', ')']
 -> Columna 'funciones': ['(', ')']
 -> Columna 'conocimientos': ['(', ')']
 -> Columna 'experiencia': ['(', ')']
 -> Columna 'experiencia_cv': ['"', '(', ')', "'", ']']
 -> Columna 'estudios_cv': ['(', ')', '"']

In [107]:
inspeccionar_contexto(df_final, '[', columnas_texto)

Buscando el carácter: '['

El carácter '[' no se encontró en las columnas indicadas.

In [108]:
inspeccionar_contexto(df_final, ']', columnas_texto)

Buscando el carácter: ']'

=== Columna 'experiencia_cv' (1 apariciones) ===
 Fila 184: ...ivo de la PES-UNI (Colaborador)  QHATUNI >>>]<<< :IV FERIA DE LIBROS, BECAS Y ARTE ||| TO...
------------------------------------------------------------

In [109]:
diccionario_hallazgos = {
    ']': ''
}

print("Aplicando reemplazos descubiertos en el contexto.\n")

for col in ['experiencia_cv']:
    for mal, bien in diccionario_hallazgos.items():
        df_final[col] = df_final[col].str.replace(mal, bien, regex=False)

Aplicando reemplazos descubiertos en el contexto.

In [110]:
patron_extranos = r'[^a-zA-Z0-9ñÑáéíóúÁÉÍÓÚüÜ\s\.\,\/\#\-\+\:\|]'
buscar_caracteres_extranos(df_final, patron_extranos)

Buscando caracteres extraños.

Se encontraron caracteres extraños en las siguientes columnas:
 -> Columna 'cargo': ['(', ')']
 -> Columna 'funciones': ['(', ')']
 -> Columna 'conocimientos': ['(', ')']
 -> Columna 'experiencia': ['(', ')']
 -> Columna 'experiencia_cv': ['"', '(', ')', "'"]
 -> Columna 'estudios_cv': ['(', ')', '"']

In [111]:
inspeccionar_contexto(df_final, '(', columnas_texto)

Buscando el carácter: '('

=== Columna 'cargo' (7 apariciones) ===
 Fila 116: ...AS TECNOLOGÍAS Y TRANSFORMACIÓN DIGITAL  >>>(<<< EGRESADOR MAYO - DICIEMBRE 2019 Y MAYO -...
 Fila 165: ...AS TECNOLOGÍAS Y TRANSFORMACIÓN DIGITAL  >>>(<<< EGRESADOR MAYO - DICIEMBRE 2019 Y MAYO -...
 Fila 183: ...Ejecutivo de Ventas / Part time  >>>(<<< Home Office)...
 Fila 191: ...AS TECNOLOGÍAS Y TRANSFORMACIÓN DIGITAL  >>>(<<< EGRESADOR MAYO - DICIEMBRE 2019 Y MAYO -...
 Fila 200: ...Ejecutivo de Ventas / Part time  >>>(<<< Home Office)...
------------------------------------------------------------
=== Columna 'funciones' (37 apariciones) ===
 Fila 7: ...quitectura de la solución a implementar  >>>(<<< IoT + IA). - Participar en la construcci...
 Fila 8: ...quitectura de la solución a implementar  >>>(<<< IoT + IA). - Participar en la construcci...
 Fila 12: ...e acuerdo a los parámetros establecidos  >>>(<<< líneas de crédito, descuentos) - Gestion...
 Fila 14: ...carreras de Ing. Mecánica o Mecatrónica  >>>(<<< Indispensable). - Experiencia mínima de ...
 Fila 15: ...ra de Ingeniería Mecánica o Mecatrónica  >>>(<<< indispensable). - Experiencia previa en ...
------------------------------------------------------------
=== Columna 'conocimientos' (57 apariciones) ===
 Fila 0: ...onocimientos de Java Script, SQL Server  >>>(<<< de preferencia).. Se valorará experienci...
 Fila 1: ...ngeniero de DISEÑO en el sector oilygas  >>>(<<< excluyente)  Experiencia en configuració...
 Fila 4: ...as de Ingeniería mecánica o mecatrónica  >>>(<<< Indispensable) Experiencia laboral de 3 ...
 Fila 5: ...iagramas PID.  Dominio de idioma inglés  >>>(<<<  no excluyente)  Disponibilidad para tra...
 Fila 6: ...as de Ingeniería mecánica o mecatrónica  >>>(<<< Indispensable) . Experiencia laboral de ...
------------------------------------------------------------
=== Columna 'experiencia' (12 apariciones) ===
 Fila 11: ... de Materiales de Construcción o afines  >>>(<<< entre 3 y 5 años) Experiencia visitando ...
 Fila 15: ...riencia previa en empresas industriales  >>>(<<< deseable)....
 Fila 16: ...lante debe pertenecer al tercio superio  >>>(<<< preferible quinto superior) por ser una ...
 Fila 21: ..., mantenimiento de sistemas hidráulicos  >>>(<<< Excluyente) ...
 Fila 22: ... mantenimiento en empresas industriales  >>>(<<< Indispensable)...
------------------------------------------------------------
=== Columna 'experiencia_cv' (41 apariciones) ===
 Fila 6: ...ES INTERPERSONALES ||| Microsoft Office  >>>(<<< Word, Excel, PowerPoint) ||| Microsoft P...
 Fila 8: ...AWS  >>>(<<< S3,IoT) ||| Desarrollo en sistema operat...
 Fila 9: ...ions ||| ESPAÑOL ||| Fundamentos de CAE  >>>(<<< Computer Aided Engineering) ||| Harnessi...
 Fila 15: ...PERSONALES ||| Ms Project ||| Ofimática  >>>(<<< Word, Publisher, etc). ||| ORGANIZACIÓN ...
 Fila 29: ...ES INTERPERSONALES ||| Microsoft Office  >>>(<<< Word, Excel, PowerPoint) ||| ORGANIZACIÓ...
------------------------------------------------------------
=== Columna 'estudios_cv' (12 apariciones) ===
 Fila 45: ...n en Inteligencia de Negocios con Excel  >>>(<<< Power Query)...
 Fila 46: ...n tablas dinámicas, funciones avanzadas  >>>(<<< BUSCARV, INDICE+COINCIDIR, etc.) y herra...
 Fila 55: ...onfiguración de protocolos industriales  >>>(<<< RS232, MODBUS, PROFINET, PROFIBUS) con i...
 Fila 63: ...ansmisión y transformadores de potencia  >>>(<<< ANSI/IEEE C37.91) ||| Centrales Hidroelé...
 Fila 108: ...de obtuve un puntaje de inglés avanzado  >>>(<<< C2)...
------------------------------------------------------------

In [112]:
inspeccionar_contexto(df_final, '"', columnas_texto)

Buscando el carácter: '"'

=== Columna 'experiencia_cv' (12 apariciones) ===
 Fila 2: ... de Investigación ABET, con el proyecto  >>>"<<< Diseño de la lógica de control de un sis...
 Fila 15: ... ORGANIZACIÓN ||| Power BI ||| Programa  >>>"<<< Impulsando talento con valores >>>"<<< -Asociaci...
 Fila 71: ... de Investigación ABET, con el proyecto  >>>"<<< Diseño de la lógica de control de un sis...
 Fila 119: ...||| ORGANIZACIÓN ||| Power BI ||| SAChe  >>>"<<< Basics of Laboratory safety >>>"<<<  ||| SAChe  >>>"<<< ...
 Fila 136: ...3D ||| Curso Taller LEAN CONSTRUCTION,,  >>>"<<< Mejorando la Productividad en la Constru...
------------------------------------------------------------
=== Columna 'estudios_cv' (2 apariciones) ===
 Fila 135: ...greso peruano de Ingeniería  de procesos >>>"<<<  aplicando la tecnología e innovación pa...
 Fila 219: ...ology in Peru. ||| Taller de Coaching -  >>>"<<< Desarrollando habilidades mediante el tr...
------------------------------------------------------------

In [114]:
display(df_final)

,id_oferta,id_usuario,target_elegibilidad,nom_facultad,nom_especialidad,cargo,funciones,conocimientos,experiencia,experiencia_cv,estudios_cv
0,34635,1002160,1,INGENIERIA INDUSTRIAL Y DE SISTEMAS,INGENIERIA DE SISTEMAS,Analista Programador Junior,"Formar parte de nuestros equipos de desarrollo, programando nuevas funcionalidades o adaptando funcionalidades existentes del ERP a partir de requerimientos internos o de clientes.. Colaborar con la documentación de las funcionalidades existentes del ERP, así como de las herramientas propietarias o de las diversas aplicaciones desarrolladas.. Participar en reuniones técnicas de programación y seguimiento.. Participar en los procesos de implementación y soporte de funcionalidades a clientes.","Conocimientos de Java Script, SQL Server (de preferencia).. Se valorará experiencia en desarrollo o uso de ERPs.. Se valorarán conocimientos de gestión de proyectos ágiles.",Con o sin experiencia,ESPAÑOL ||| Excel ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| Jira Software ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Microsoft Office ||| Microsoft Power BI ||| ORGANIZACIÓN ||| Programación en Python ||| SQL Server ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,NaN
1,32700,2256,1,INGENIERIA MECANICA,INGENIERIA MECATRONICA,Ingeniero de Instrumentación,"Desarrollar la ingeniería de su especialidad de Instrumentación para los proyectos llevados a cabo por la cía, cumpliendo con los plazos y parámetros de calidad y costos establecidos.","Profesional titulado de las carreras de Ing. Electrónica, Mecatrónica o afines. Experiencia como ingeniero de DISEÑO en el sector oilygas (excluyente) Experiencia en configuración de PLC, sistemas de control, sistemas de seguridad. Experiencia mínima 03 años a más. Dominio de idioma inglés comprobado.",Junior mínimo 03 años en ingeniería de diseño. Senior no menor 10 años en ingeniería de diseño,"||| Autocad ||| Ejecutivo con experiencia en implementacion y monitoreo de proyectos de desarrollo, estudios de mercado, gestion de ensayos de laboratorio, reformulacion de normas gubernamentales, gestion de sistemas de informacion y administrador de plataforma web. Conocimiento de normativas de servicios publicos, evaluacion de procesos de contratacion del estado. Capacidad de trabajo en equipo y bajo presión, asumir retos y orientado a resultados ||| FRANCÉS ||| Habilidades sociales: Empatía, Liderazgo, Interrelación con otros, Escucha activa, Persuasión, Capacidad de comunicación. Habilidades profesionales: Trabajo en equipo, Liderazgo, Negociación, Control del estrés, Racionalización, Capacidad analítica, Capacidad de síntesis, Argumentación, Innovación y creatividad, Iniciativa ||| IBM - Maximo Asset Management ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Ofimatica ||| ORGANIZACIÓN ||| PORTUGUÉS ||| SAP - M",Diseño de experimentos
2,34733,10078,1,INGENIERIA MECANICA,INGENIERIA MECATRONICA,GERENTE DE OPERACIONES,"Liderar el plan estratégico de operaciones en mina.. Liderar la concepción, ingeniería, valorización, construcción y supervisión de proyectos de desarrollo en mina.. Analizar las propuestas técnicas para los proyectos mineros.",Conocimientos en instalación de proyectos mineros,Experiencia mínima de 10 años liderando proyectos mineros,"Entrenamiento intensivo en los temas claves de Automatización Industrial - Webinar Week 2023 ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÓN ||| Participación como proyectista en la Feria y Concurso de Proyectos de Investigación ABET, con el proyecto ""Diseño de la lógica de control de un sistema de envasado de aceite y posterior embarque de l ||| Participación como proyectista en la Feria y Concurso de Proyectos de Investigación ABET, con el proyecto ""Sistema eficiente de riego inteligente para áreas verdes de zonas urbanas."" ||| Participación en la capacitación virtual en IDENTIFICACION DE PELIGROS, EVALUACION DE RIESGOS Y MEDIDAS DE CONTROL ||| REGLAMENTO INTERNO DE SEGURIDAD Y SALUD EN EL TRABAJO ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN ||| Trabajos en Altura",NaN
3,32671,6323,1,INGENIERIA MECANICA,INGENIERIA MECANICA Y ELECTRICA,Cotizador de Servicio Técnico Comercial,"01.Apoyar en el soporte técnico a los Ingenieros de Ventas, Vendedor de Servicios, clientes internos y externos, vía telefónica, mail u otro. 02.Elaborar propuestas técnicas o fichas técnicas de la línea STC. 03.Elaborar cotizaciones STC por medio del uso del sistema SAP, así como los entregables que serán dirigidos a los clientes, mediante el uso de plantillas del área. 04.Apoyar en la elaboración de las presentaciones de las propuestas técnicas-comerciales a los Ingenieros de Ventas. Etc.",Basicos,No se requiere experiencia previa en el puesto.,||| Ansys ||| AutoCad ||| Capacidad analítica y juicio critico ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| Inventor ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Microsoft office ||| MS Project ||| ORGANIZACIÓN ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,"Curso de capacitación llevado a cabo en Buenos Aires para mantenimineto de compresores de aire y oxigeno, secadores, PSA e instrumentacion de plantas de Oxigeno medicinal. ||| Inventor - Nivel Avanzado"
4,36568,1002976,1,INGENIERIA MECANICA,INGENIERIA MECANICA,Ingeniero de Mantenimiento Mecánico,"Cumplir con el programa de mantenimiento preventivo y correctivo para asegurar la operación continua de la planta. Supervisar e inspeccionar la planta para asegurar el buen funcionamiento de las máquinas en general. Supervisar la ejecución de los trabajos de mantenimiento correctivo y preventivo de la planta. Mantener registros precisos de mantenimiento, informes de incidentes y mejoras implementadas, proporcionando datos para análisis y toma de decisiones estratégicas. Implementar mejoras en lo",Bachiller o titulado de las carreras de Ingeniería mecánica o mecatrónica (Indispensable) Experiencia laboral de 3 años mínimo en el área de mantenimiento en empresas industriales (Indispensable) Office nivel avanzado. Disponibilidad para laborar en la zona sur de Lima,N,AutoCAD ||| Autodesk Inventor ||| CERTIFICADO DE AUTOCAD NIVEL INTERMEDIO ||| CERTIFICADO DE EXCEL NIVEL AVANZADO ||| CERTIFICADO DE KEY USER SAP PM ||| Excel ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Matlab ||| MS Office ||| ORGANIZACIÓN ||| Power BI ||| Python ||| Revit ||| SAP PM y SAP MM ||| SQL Server ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,"||| calculo de la carga térmica y estudio de carta psicométrica ||| Estudio de la Ingenieria de Mantenimiento Correctivo, Preventivo y Predictivo, también el estudio de la fiabilidad, confiabilidad y el análisis de Weibull. ||| layout, bloques estáticos y dinámicos, planos, etc. ||| Secuencia de comandos e instrucciones grabadas en excel, generar informes y manipular datos, automatizar tareas repetitivas o complejas. ||| Transacciones de mantenimiento, Datos Maestros, Gestión de avisos de mantenimiento, Gestión de ordenes de mantenimiento, Mantenimiento preventivo o planificado y sistemas de información o reportes"
...,...,...,...,...,...,...,...,...,...,...,...
215,26715,2406,0,INGENIERIA QUIMICA Y TEXTIL,INGENIERIA QUIMICA,Ejecutivo de Ventas / Part time (Home Office),NaN,NaN,N,"||| AspenHysys ||| AutoCAD ||| Estudiante del 9no ciclo de Ingeniería Química en la Universidad Nacional de Ingeniería. Me caracterizo por ser una persona proactiva, entusiasta y con muchas ganas de aprender. Cuento con un gran interés en los procesos y deseo iniciar una línea de carrera en dicha área. ||| Excel Empresarial ||| Gestión Ambiental ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| ITALIANO ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Minitab ||| MS Excel ||| MS Word ||| ORGANIZACIÓN ||| Phyton ||| PowerBI ||| SAP ERP ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN","||| Citizen development ||| Gestión ambiental en la industria, tratamiento de residuos sólidos. Contaminación del agua, suelo, atmósfera. Norma ISO 14001: 2015. ||| Normas ISO 9001, ISO 45001, ISO 14001"
216,13460,1777,0,INGENIERIA QUIMICA Y TEXTIL,INGENIERIA QUIMICA,Practicantes de Ingeniera Qumica,- Efectuar visitas guiadas de acuerdo a la programación diaria de la cartera de Clientes de la Empresa. - Elaborar Informes de carácter Técnico-Ingenieril de las visitas realizadas. - Participar activamente en los Mantenimientos de Planta programados por la Empresa. - Mantener y cautelar adecuadamente los instrumentos de monitoreo de Planta a su cargo. - Cualquier otra función que le asigne el Jefe Inmediato.,Programa Informático Office a nivel Intermedio. Deseable Curso de Tratamiento de Agua.,N,||| EXCEL ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÓN ||| POWERPOINT ||| PROJECT ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,N
217,22619,86,0,INGENIERIA CIVIL,INGENIERIA CIVIL,Ingeniero Civil Junior.,NaN,NaN,N,||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÓN ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,N
218,8558,244,0,INGENIERIA INDUSTRIAL Y DE SISTEMAS,INGENIERIA DE SISTEMAS,Practicante de Ingeniería Industrial,"Desarrollo, control y armado de los sistemas de calidad, SSO y medio ambiente Verificación del cumplimiento de SIG Chequeo de las desviaciones de SIG y desarrollo de sistemas/métodos para evitar la desviación Preparación para auditorías relacionadas a estos sistemas",Normas ISO 9000 Normas ISO 14000 Normas OHSAS 18000 Sistemas integrados de gestión Herramientas de calidad Gestión de procesos Seguridad y salud ocupacional Gestión de calidad total Ingeniería y gestión ambiental,N,"||| Bizagui- Modeler ||| Estudiante de Ing. Sistemas de la Universidad Nacional de Ingeniería, perteneciente al tercio superior, con conocimientos y manejo de Microsoft Excel 2016, SQL SERVER - Implementación y Project, Gestión de Proyectos y del idioma inglés a nivel básico. Me considero autodidacta, proactivo, puntual, innovador, analítico, creativo, responsable, con habilidad para trabajar en equipo y bajo presión, con capacidad para resolver problemas, deseo de superación e iniciativa propia. ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| MS EXCEL ||| MS Project ||| MS SQL Server ||| MS Visio ||| ORGANIZACIÓN ||| Pro-Model 2014 ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN","Conocimientos acerca de las áreas de conocimiento, sobre la documentación en los entregables. El objetivo principal de la Gestión de Proyectos es administrar, planificar, coordinar, seguimiento y con ||| Entender las definiciones, objetivos y técnicas del modelado de procesos de negocio. Definir y proveer una notación estándar que sea fácilmente entendible por los involucrados en el proceso de negocio"
219,9329,3758,0,INGENIERIA CIVIL,INGENIERIA CIVIL,Jefe de Campo,"- Supervisar y distribuir las actividades del personal a cargo de acuerdo a los proyectos establecidos. - Organizar y dirigir el equipo humano así como los medios productivos de la obra para obtener los resultados en los plazos establecidos. - Supervisar, controlar la distribución y recepción de los materiales requeridos para cada actividad en particular. - Coordinar con el área de proyectos los materiales que requieren para cada proyecto y proponer aquellos que se requieran para casos particulares. - Participar en la fase de construcción del proyecto aportando soluciones e ideas que faciliten la operación. - Asistir y participar como representante de la empresa en las reuniones de coordinación, seguridad. - Cumplir y hacer cumplir las normas y procedimientos de seguridad y salud en el trabajo establecidos por la organización.",Microsoft Office nivel Intermedio AUTOCAD 3D MAX Photoshop,N,"ArcGis ||| Auto CAD, ||| Civil3D ||| Emprendedor, analítico, pasión por aprender, innovador, liderazgo de equipos, comunicación asertiva, dirección y planeamiento estratégico, gestión del riesgo, orientación a resultados, capacidad de análisis y alto sentido de la responsabilidad. ||| ESPAÑOL ||| ETABS ||| Formar parte de una empresa de alto prestigio. Asi permita el desarrolllo de la empresa a través del crecimiento profesional, el logro de las metas efizcamente y mejoramiento continuo de conocimientos, habilidades, fortalezas e iniciativa ||| INGLÉS ||| JAPONÉS ||| Ms Office ||| Ms Project ||| Primavera, ||| Revit Architecture, ||| S10, ||| SAP 2000, ||| ""Profesional de Ingeniería Civil con MBA en curso con 5 años de experiencia. Especialista en Proyectos y Obras Civiles. Inglés avanzado.""","Gestión de Proyectos ||| Gestión en la Construcción ||| Results of the SATREPS Project: Enhancement of Earthquake and Tsunami Disaster Mitigation Technology in Peru. ||| Taller de Coaching - ""Desarrollando habilidades mediante el trabajo en equipo"" ||| Taller de Liderazgo - ""Liderando equipos"". ||| Taller de Seguridad en Obra ||| Valorización y Liquidación de Contratos de Obra"

In [115]:
import numpy as np

print("Tratamiento de valores nulos.\n")

valores_nulos_texto = ['N', 'NULL', 'null', 'None', 'NaN']

for col in columnas_texto:
    if col in df_final.columns:
        df_final[col] = df_final[col].replace(valores_nulos_texto, np.nan, regex=False)
        
        df_final[col] = df_final[col].fillna('')
        
        df_final[col] = df_final[col].astype(str)

display(df_final)

Tratamiento de valores nulos.

,id_oferta,id_usuario,target_elegibilidad,nom_facultad,nom_especialidad,cargo,funciones,conocimientos,experiencia,experiencia_cv,estudios_cv
0,34635,1002160,1,INGENIERIA INDUSTRIAL Y DE SISTEMAS,INGENIERIA DE SISTEMAS,Analista Programador Junior,"Formar parte de nuestros equipos de desarrollo, programando nuevas funcionalidades o adaptando funcionalidades existentes del ERP a partir de requerimientos internos o de clientes.. Colaborar con la documentación de las funcionalidades existentes del ERP, así como de las herramientas propietarias o de las diversas aplicaciones desarrolladas.. Participar en reuniones técnicas de programación y seguimiento.. Participar en los procesos de implementación y soporte de funcionalidades a clientes.","Conocimientos de Java Script, SQL Server (de preferencia).. Se valorará experiencia en desarrollo o uso de ERPs.. Se valorarán conocimientos de gestión de proyectos ágiles.",Con o sin experiencia,ESPAÑOL ||| Excel ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| Jira Software ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Microsoft Office ||| Microsoft Power BI ||| ORGANIZACIÓN ||| Programación en Python ||| SQL Server ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,
1,32700,2256,1,INGENIERIA MECANICA,INGENIERIA MECATRONICA,Ingeniero de Instrumentación,"Desarrollar la ingeniería de su especialidad de Instrumentación para los proyectos llevados a cabo por la cía, cumpliendo con los plazos y parámetros de calidad y costos establecidos.","Profesional titulado de las carreras de Ing. Electrónica, Mecatrónica o afines. Experiencia como ingeniero de DISEÑO en el sector oilygas (excluyente) Experiencia en configuración de PLC, sistemas de control, sistemas de seguridad. Experiencia mínima 03 años a más. Dominio de idioma inglés comprobado.",Junior mínimo 03 años en ingeniería de diseño. Senior no menor 10 años en ingeniería de diseño,"||| Autocad ||| Ejecutivo con experiencia en implementacion y monitoreo de proyectos de desarrollo, estudios de mercado, gestion de ensayos de laboratorio, reformulacion de normas gubernamentales, gestion de sistemas de informacion y administrador de plataforma web. Conocimiento de normativas de servicios publicos, evaluacion de procesos de contratacion del estado. Capacidad de trabajo en equipo y bajo presión, asumir retos y orientado a resultados ||| FRANCÉS ||| Habilidades sociales: Empatía, Liderazgo, Interrelación con otros, Escucha activa, Persuasión, Capacidad de comunicación. Habilidades profesionales: Trabajo en equipo, Liderazgo, Negociación, Control del estrés, Racionalización, Capacidad analítica, Capacidad de síntesis, Argumentación, Innovación y creatividad, Iniciativa ||| IBM - Maximo Asset Management ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Ofimatica ||| ORGANIZACIÓN ||| PORTUGUÉS ||| SAP - M",Diseño de experimentos
2,34733,10078,1,INGENIERIA MECANICA,INGENIERIA MECATRONICA,GERENTE DE OPERACIONES,"Liderar el plan estratégico de operaciones en mina.. Liderar la concepción, ingeniería, valorización, construcción y supervisión de proyectos de desarrollo en mina.. Analizar las propuestas técnicas para los proyectos mineros.",Conocimientos en instalación de proyectos mineros,Experiencia mínima de 10 años liderando proyectos mineros,"Entrenamiento intensivo en los temas claves de Automatización Industrial - Webinar Week 2023 ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÓN ||| Participación como proyectista en la Feria y Concurso de Proyectos de Investigación ABET, con el proyecto ""Diseño de la lógica de control de un sistema de envasado de aceite y posterior embarque de l ||| Participación como proyectista en la Feria y Concurso de Proyectos de Investigación ABET, con el proyecto ""Sistema eficiente de riego inteligente para áreas verdes de zonas urbanas."" ||| Participación en la capacitación virtual en IDENTIFICACION DE PELIGROS, EVALUACION DE RIESGOS Y MEDIDAS DE CONTROL ||| REGLAMENTO INTERNO DE SEGURIDAD Y SALUD EN EL TRABAJO ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN ||| Trabajos en Altura",
3,32671,6323,1,INGENIERIA MECANICA,INGENIERIA MECANICA Y ELECTRICA,Cotizador de Servicio Técnico Comercial,"01.Apoyar en el soporte técnico a los Ingenieros de Ventas, Vendedor de Servicios, clientes internos y externos, vía telefónica, mail u otro. 02.Elaborar propuestas técnicas o fichas técnicas de la línea STC. 03.Elaborar cotizaciones STC por medio del uso del sistema SAP, así como los entregables que serán dirigidos a los clientes, mediante el uso de plantillas del área. 04.Apoyar en la elaboración de las presentaciones de las propuestas técnicas-comerciales a los Ingenieros de Ventas. Etc.",Basicos,No se requiere experiencia previa en el puesto.,||| Ansys ||| AutoCad ||| Capacidad analítica y juicio critico ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| Inventor ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Microsoft office ||| MS Project ||| ORGANIZACIÓN ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,"Curso de capacitación llevado a cabo en Buenos Aires para mantenimineto de compresores de aire y oxigeno, secadores, PSA e instrumentacion de plantas de Oxigeno medicinal. ||| Inventor - Nivel Avanzado"
4,36568,1002976,1,INGENIERIA MECANICA,INGENIERIA MECANICA,Ingeniero de Mantenimiento Mecánico,"Cumplir con el programa de mantenimiento preventivo y correctivo para asegurar la operación continua de la planta. Supervisar e inspeccionar la planta para asegurar el buen funcionamiento de las máquinas en general. Supervisar la ejecución de los trabajos de mantenimiento correctivo y preventivo de la planta. Mantener registros precisos de mantenimiento, informes de incidentes y mejoras implementadas, proporcionando datos para análisis y toma de decisiones estratégicas. Implementar mejoras en lo",Bachiller o titulado de las carreras de Ingeniería mecánica o mecatrónica (Indispensable) Experiencia laboral de 3 años mínimo en el área de mantenimiento en empresas industriales (Indispensable) Office nivel avanzado. Disponibilidad para laborar en la zona sur de Lima,,AutoCAD ||| Autodesk Inventor ||| CERTIFICADO DE AUTOCAD NIVEL INTERMEDIO ||| CERTIFICADO DE EXCEL NIVEL AVANZADO ||| CERTIFICADO DE KEY USER SAP PM ||| Excel ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Matlab ||| MS Office ||| ORGANIZACIÓN ||| Power BI ||| Python ||| Revit ||| SAP PM y SAP MM ||| SQL Server ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,"||| calculo de la carga térmica y estudio de carta psicométrica ||| Estudio de la Ingenieria de Mantenimiento Correctivo, Preventivo y Predictivo, también el estudio de la fiabilidad, confiabilidad y el análisis de Weibull. ||| layout, bloques estáticos y dinámicos, planos, etc. ||| Secuencia de comandos e instrucciones grabadas en excel, generar informes y manipular datos, automatizar tareas repetitivas o complejas. ||| Transacciones de mantenimiento, Datos Maestros, Gestión de avisos de mantenimiento, Gestión de ordenes de mantenimiento, Mantenimiento preventivo o planificado y sistemas de información o reportes"
...,...,...,...,...,...,...,...,...,...,...,...
215,26715,2406,0,INGENIERIA QUIMICA Y TEXTIL,INGENIERIA QUIMICA,Ejecutivo de Ventas / Part time (Home Office),,,,"||| AspenHysys ||| AutoCAD ||| Estudiante del 9no ciclo de Ingeniería Química en la Universidad Nacional de Ingeniería. Me caracterizo por ser una persona proactiva, entusiasta y con muchas ganas de aprender. Cuento con un gran interés en los procesos y deseo iniciar una línea de carrera en dicha área. ||| Excel Empresarial ||| Gestión Ambiental ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| ITALIANO ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| Minitab ||| MS Excel ||| MS Word ||| ORGANIZACIÓN ||| Phyton ||| PowerBI ||| SAP ERP ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN","||| Citizen development ||| Gestión ambiental en la industria, tratamiento de residuos sólidos. Contaminación del agua, suelo, atmósfera. Norma ISO 14001: 2015. ||| Normas ISO 9001, ISO 45001, ISO 14001"
216,13460,1777,0,INGENIERIA QUIMICA Y TEXTIL,INGENIERIA QUIMICA,Practicantes de Ingeniera Qumica,- Efectuar visitas guiadas de acuerdo a la programación diaria de la cartera de Clientes de la Empresa. - Elaborar Informes de carácter Técnico-Ingenieril de las visitas realizadas. - Participar activamente en los Mantenimientos de Planta programados por la Empresa. - Mantener y cautelar adecuadamente los instrumentos de monitoreo de Planta a su cargo. - Cualquier otra función que le asigne el Jefe Inmediato.,Programa Informático Office a nivel Intermedio. Deseable Curso de Tratamiento de Agua.,,||| EXCEL ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÓN ||| POWERPOINT ||| PROJECT ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,
217,22619,86,0,INGENIERIA CIVIL,INGENIERIA CIVIL,Ingeniero Civil Junior.,,,,||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| ORGANIZACIÓN ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN,
218,8558,244,0,INGENIERIA INDUSTRIAL Y DE SISTEMAS,INGENIERIA DE SISTEMAS,Practicante de Ingeniería Industrial,"Desarrollo, control y armado de los sistemas de calidad, SSO y medio ambiente Verificación del cumplimiento de SIG Chequeo de las desviaciones de SIG y desarrollo de sistemas/métodos para evitar la desviación Preparación para auditorías relacionadas a estos sistemas",Normas ISO 9000 Normas ISO 14000 Normas OHSAS 18000 Sistemas integrados de gestión Herramientas de calidad Gestión de procesos Seguridad y salud ocupacional Gestión de calidad total Ingeniería y gestión ambiental,,"||| Bizagui- Modeler ||| Estudiante de Ing. Sistemas de la Universidad Nacional de Ingeniería, perteneciente al tercio superior, con conocimientos y manejo de Microsoft Excel 2016, SQL SERVER - Implementación y Project, Gestión de Proyectos y del idioma inglés a nivel básico. Me considero autodidacta, proactivo, puntual, innovador, analítico, creativo, responsable, con habilidad para trabajar en equipo y bajo presión, con capacidad para resolver problemas, deseo de superación e iniciativa propia. ||| INGLÉS ||| INNOVACIÓN Y CREATIVIDAD ||| LIDERAZGO Y CAPACIDAD DE GESTIÓN ||| MANEJO DE RELACIONES INTERPERSONALES ||| MS EXCEL ||| MS Project ||| MS SQL Server ||| MS Visio ||| ORGANIZACIÓN ||| Pro-Model 2014 ||| TOMA DE DECISIONES ||| TRABAJO BAJO PRESIÓN","Conocimientos acerca de las áreas de conocimiento, sobre la documentación en los entregables. El objetivo principal de la Gestión de Proyectos es administrar, planificar, coordinar, seguimiento y con ||| Entender las definiciones, objetivos y técnicas del modelado de procesos de negocio. Definir y proveer una notación estándar que sea fácilmente entendible por los involucrados en el proceso de negocio"
219,9329,3758,0,INGENIERIA CIVIL,INGENIERIA CIVIL,Jefe de Campo,"- Supervisar y distribuir las actividades del personal a cargo de acuerdo a los proyectos establecidos. - Organizar y dirigir el equipo humano así como los medios productivos de la obra para obtener los resultados en los plazos establecidos. - Supervisar, controlar la distribución y recepción de los materiales requeridos para cada actividad en particular. - Coordinar con el área de proyectos los materiales que requieren para cada proyecto y proponer aquellos que se requieran para casos particulares. - Participar en la fase de construcción del proyecto aportando soluciones e ideas que faciliten la operación. - Asistir y participar como representante de la empresa en las reuniones de coordinación, seguridad. - Cumplir y hacer cumplir las normas y procedimientos de seguridad y salud en el trabajo establecidos por la organización.",Microsoft Office nivel Intermedio AUTOCAD 3D MAX Photoshop,,"ArcGis ||| Auto CAD, ||| Civil3D ||| Emprendedor, analítico, pasión por aprender, innovador, liderazgo de equipos, comunicación asertiva, dirección y planeamiento estratégico, gestión del riesgo, orientación a resultados, capacidad de análisis y alto sentido de la responsabilidad. ||| ESPAÑOL ||| ETABS ||| Formar parte de una empresa de alto prestigio. Asi permita el desarrolllo de la empresa a través del crecimiento profesional, el logro de las metas efizcamente y mejoramiento continuo de conocimientos, habilidades, fortalezas e iniciativa ||| INGLÉS ||| JAPONÉS ||| Ms Office ||| Ms Project ||| Primavera, ||| Revit Architecture, ||| S10, ||| SAP 2000, ||| ""Profesional de Ingeniería Civil con MBA en curso con 5 años de experiencia. Especialista en Proyectos y Obras Civiles. Inglés avanzado.""","Gestión de Proyectos ||| Gestión en la Construcción ||| Results of the SATREPS Project: Enhancement of Earthquake and Tsunami Disaster Mitigation Technology in Peru. ||| Taller de Coaching - ""Desarrollando habilidades mediante el trabajo en equipo"" ||| Taller de Liderazgo - ""Liderando equipos"". ||| Taller de Seguridad en Obra ||| Valorización y Liquidación de Contratos de Obra"

In [117]:
print("Eliminando espacios y puntos múltiples.\n")

for col in columnas_texto:
    if col in df_final.columns:
        df_final[col] = df_final[col].str.replace(r'\.{2,}', '.', regex=True)
        
        df_final[col] = df_final[col].str.replace(r'\s+', ' ', regex=True)
        
        df_final[col] = df_final[col].str.strip()

Eliminando espacios y puntos múltiples.

In [118]:
inspeccionar_contexto(df_final, '  ', columnas_texto)
inspeccionar_contexto(df_final, '..', columnas_texto)

Buscando el carácter: '  '

El carácter '  ' no se encontró en las columnas indicadas.
Buscando el carácter: '..'

El carácter '..' no se encontró en las columnas indicadas.

In [119]:
df_final.to_csv(
    '../datos/dataset_nlp_utf16_final.csv', 
    index=False, 
    encoding='utf-16', 
    sep=',', 
    quoting=csv.QUOTE_ALL, 
    escapechar='\\'
)

print(f"Archivo final: 'dataset_nlp_utf16_final.csv'")
print(f"Total de filas: {df_final.shape[0]}")
print(f"Total de columnas: {df_final.shape[1]}")

Archivo final: 'dataset_nlp_utf16_final.csv'
Total de filas: 220
Total de columnas: 11